// /shared/proto/ai.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ai.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CriterionToGrade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"` // "behavioral" | "structural" | "conceptual"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CriterionToGrade) Reset() {
	*x = CriterionToGrade{}
	mi := &file_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CriterionToGrade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CriterionToGrade) ProtoMessage() {}

func (x *CriterionToGrade) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CriterionToGrade.ProtoReflect.Descriptor instead.
func (*CriterionToGrade) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{0}
}

func (x *CriterionToGrade) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CriterionToGrade) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CriterionToGrade) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type GradeCriteriaRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	UserEmail  string                 `protobuf:"bytes,1,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	ProjectId  string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	PhaseTitle string                 `protobuf:"bytes,3,opt,name=phase_title,json=phaseTitle,proto3" json:"phase_title,omitempty"`
	// Context only — criteria are what gets graded. Included so the model can
	// tell which phase it's in and stay out of later phases' concerns.
	PhaseGoal     string              `protobuf:"bytes,4,opt,name=phase_goal,json=phaseGoal,proto3" json:"phase_goal,omitempty"`
	Criteria      []*CriterionToGrade `protobuf:"bytes,5,rep,name=criteria,proto3" json:"criteria,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradeCriteriaRequest) Reset() {
	*x = GradeCriteriaRequest{}
	mi := &file_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeCriteriaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeCriteriaRequest) ProtoMessage() {}

func (x *GradeCriteriaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeCriteriaRequest.ProtoReflect.Descriptor instead.
func (*GradeCriteriaRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{1}
}

func (x *GradeCriteriaRequest) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *GradeCriteriaRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GradeCriteriaRequest) GetPhaseTitle() string {
	if x != nil {
		return x.PhaseTitle
	}
	return ""
}

func (x *GradeCriteriaRequest) GetPhaseGoal() string {
	if x != nil {
		return x.PhaseGoal
	}
	return ""
}

func (x *GradeCriteriaRequest) GetCriteria() []*CriterionToGrade {
	if x != nil {
		return x.Criteria
	}
	return nil
}

type CriterionVerdict struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	CriterionId string                 `protobuf:"bytes,1,opt,name=criterion_id,json=criterionId,proto3" json:"criterion_id,omitempty"`
	Passed      bool                   `protobuf:"varint,2,opt,name=passed,proto3" json:"passed,omitempty"`
	// Required when passed. A pass with no citable evidence is downgraded to a
	// failure by the caller — an unevidenced claim is exactly what this design
	// exists to reject.
	EvidencePath  string `protobuf:"bytes,3,opt,name=evidence_path,json=evidencePath,proto3" json:"evidence_path,omitempty"`
	EvidenceLines string `protobuf:"bytes,4,opt,name=evidence_lines,json=evidenceLines,proto3" json:"evidence_lines,omitempty"`
	EvidenceQuote string `protobuf:"bytes,5,opt,name=evidence_quote,json=evidenceQuote,proto3" json:"evidence_quote,omitempty"`
	// One sentence. Shown to the user when the criterion failed.
	Reasoning string `protobuf:"bytes,6,opt,name=reasoning,proto3" json:"reasoning,omitempty"`
	// True when this criterion could not be graded at all (model error, malformed
	// response). Not the same as failing: the user's work wasn't judged.
	Ungraded      bool `protobuf:"varint,7,opt,name=ungraded,proto3" json:"ungraded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CriterionVerdict) Reset() {
	*x = CriterionVerdict{}
	mi := &file_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CriterionVerdict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CriterionVerdict) ProtoMessage() {}

func (x *CriterionVerdict) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CriterionVerdict.ProtoReflect.Descriptor instead.
func (*CriterionVerdict) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{2}
}

func (x *CriterionVerdict) GetCriterionId() string {
	if x != nil {
		return x.CriterionId
	}
	return ""
}

func (x *CriterionVerdict) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *CriterionVerdict) GetEvidencePath() string {
	if x != nil {
		return x.EvidencePath
	}
	return ""
}

func (x *CriterionVerdict) GetEvidenceLines() string {
	if x != nil {
		return x.EvidenceLines
	}
	return ""
}

func (x *CriterionVerdict) GetEvidenceQuote() string {
	if x != nil {
		return x.EvidenceQuote
	}
	return ""
}

func (x *CriterionVerdict) GetReasoning() string {
	if x != nil {
		return x.Reasoning
	}
	return ""
}

func (x *CriterionVerdict) GetUngraded() bool {
	if x != nil {
		return x.Ungraded
	}
	return false
}

type GradeCriteriaResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Verdicts []*CriterionVerdict    `protobuf:"bytes,1,rep,name=verdicts,proto3" json:"verdicts,omitempty"`
	// Model that produced these, recorded so a bad batch can be traced.
	Model         string `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradeCriteriaResponse) Reset() {
	*x = GradeCriteriaResponse{}
	mi := &file_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeCriteriaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeCriteriaResponse) ProtoMessage() {}

func (x *GradeCriteriaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeCriteriaResponse.ProtoReflect.Descriptor instead.
func (*GradeCriteriaResponse) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{3}
}

func (x *GradeCriteriaResponse) GetVerdicts() []*CriterionVerdict {
	if x != nil {
		return x.Verdicts
	}
	return nil
}

func (x *GradeCriteriaResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"` // "user" | "assistant"
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_ai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{4}
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ChatRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserEmail      string                 `protobuf:"bytes,1,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	ProjectId      string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	PhaseId        string                 `protobuf:"bytes,3,opt,name=phase_id,json=phaseId,proto3" json:"phase_id,omitempty"`
	ActiveFilePath string                 `protobuf:"bytes,4,opt,name=active_file_path,json=activeFilePath,proto3" json:"active_file_path,omitempty"` // empty if no file is open
	Message        string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`                                       // latest user message
	History        []*ChatMessage         `protobuf:"bytes,6,rep,name=history,proto3" json:"history,omitempty"`                                       // prior turns, oldest first
	// "" or "chat" = full agentic assistant (tool-calling, multi-file context).
	// "explain" = direct single-shot call, no tools, no file-fetching loop —
	// used for the cheap Option+Click "explain this" flow.
	// "review" = grades a phase submission. Inspects the user's actual project
	// files via tool calls and ends its reply with a line reading exactly
	// "VERDICT: MET" or "VERDICT: NOT MET".
	//
	// That verdict line is a machine-read contract, not prose: UserProjectService
	// .SubmitPhaseReview parses it server-side to decide whether to advance the
	// phase. Never call this mode directly from an end-user client and act on the
	// result — a caller that grades itself is not a gate. Route reviews through
	// SubmitPhaseReview, which is the only component that should interpret this.
	Mode string `protobuf:"bytes,7,opt,name=mode,proto3" json:"mode,omitempty"`
	// Client-supplied summary of the user's current project and task, e.g.
	// "Project: Recipe Tracker (React, Node) — Phase 2: State Management".
	// The client already holds this in memory (active project/phase
	// selection); pushing it here is cheaper than the service re-deriving it
	// via extra user-service calls.
	CurrentTask string `protobuf:"bytes,8,opt,name=current_task,json=currentTask,proto3" json:"current_task,omitempty"`
	// 0 = normal, operate on the live editable project. > 0 = the user is
	// viewing a past phase's frozen snapshot (read-only) — list_files/
	// read_file and the active-file context should read from that phase's
	// PhaseSnapshotFile tree instead of the live ProjectFile tree.
	SnapshotPhaseNumber int32 `protobuf:"varint,9,opt,name=snapshot_phase_number,json=snapshotPhaseNumber,proto3" json:"snapshot_phase_number,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_ai_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{5}
}

func (x *ChatRequest) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *ChatRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ChatRequest) GetPhaseId() string {
	if x != nil {
		return x.PhaseId
	}
	return ""
}

func (x *ChatRequest) GetActiveFilePath() string {
	if x != nil {
		return x.ActiveFilePath
	}
	return ""
}

func (x *ChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatRequest) GetHistory() []*ChatMessage {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *ChatRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *ChatRequest) GetCurrentTask() string {
	if x != nil {
		return x.CurrentTask
	}
	return ""
}

func (x *ChatRequest) GetSnapshotPhaseNumber() int32 {
	if x != nil {
		return x.SnapshotPhaseNumber
	}
	return 0
}

type ChatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One text delta of the reply. Concatenate all deltas received on the
	// stream, in order, to reconstruct the full message.
	Reply         string `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_ai_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{6}
}

func (x *ChatResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

type GradeAnswerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	CorrectAnswer string                 `protobuf:"bytes,2,opt,name=correct_answer,json=correctAnswer,proto3" json:"correct_answer,omitempty"`
	Explanation   string                 `protobuf:"bytes,3,opt,name=explanation,proto3" json:"explanation,omitempty"`
	QuestionType  string                 `protobuf:"bytes,4,opt,name=question_type,json=questionType,proto3" json:"question_type,omitempty"` // "code_completion" | "debug"
	UserAnswer    string                 `protobuf:"bytes,5,opt,name=user_answer,json=userAnswer,proto3" json:"user_answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradeAnswerRequest) Reset() {
	*x = GradeAnswerRequest{}
	mi := &file_ai_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeAnswerRequest) ProtoMessage() {}

func (x *GradeAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeAnswerRequest.ProtoReflect.Descriptor instead.
func (*GradeAnswerRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{7}
}

func (x *GradeAnswerRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *GradeAnswerRequest) GetCorrectAnswer() string {
	if x != nil {
		return x.CorrectAnswer
	}
	return ""
}

func (x *GradeAnswerRequest) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *GradeAnswerRequest) GetQuestionType() string {
	if x != nil {
		return x.QuestionType
	}
	return ""
}

func (x *GradeAnswerRequest) GetUserAnswer() string {
	if x != nil {
		return x.UserAnswer
	}
	return ""
}

type GradeAnswerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsCorrect     bool                   `protobuf:"varint,1,opt,name=is_correct,json=isCorrect,proto3" json:"is_correct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradeAnswerResponse) Reset() {
	*x = GradeAnswerResponse{}
	mi := &file_ai_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeAnswerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeAnswerResponse) ProtoMessage() {}

func (x *GradeAnswerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeAnswerResponse.ProtoReflect.Descriptor instead.
func (*GradeAnswerResponse) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{8}
}

func (x *GradeAnswerResponse) GetIsCorrect() bool {
	if x != nil {
		return x.IsCorrect
	}
	return false
}

var File_ai_proto protoreflect.FileDescriptor

const file_ai_proto_rawDesc = "" +
	"\n" +
	"\bai.proto\x12\x02ai\"J\n" +
	"\x10CriterionToGrade\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\"\xc6\x01\n" +
	"\x14GradeCriteriaRequest\x12\x1d\n" +
	"\n" +
	"user_email\x18\x01 \x01(\tR\tuserEmail\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x1f\n" +
	"\vphase_title\x18\x03 \x01(\tR\n" +
	"phaseTitle\x12\x1d\n" +
	"\n" +
	"phase_goal\x18\x04 \x01(\tR\tphaseGoal\x120\n" +
	"\bcriteria\x18\x05 \x03(\v2\x14.ai.CriterionToGradeR\bcriteria\"\xfa\x01\n" +
	"\x10CriterionVerdict\x12!\n" +
	"\fcriterion_id\x18\x01 \x01(\tR\vcriterionId\x12\x16\n" +
	"\x06passed\x18\x02 \x01(\bR\x06passed\x12#\n" +
	"\revidence_path\x18\x03 \x01(\tR\fevidencePath\x12%\n" +
	"\x0eevidence_lines\x18\x04 \x01(\tR\revidenceLines\x12%\n" +
	"\x0eevidence_quote\x18\x05 \x01(\tR\revidenceQuote\x12\x1c\n" +
	"\treasoning\x18\x06 \x01(\tR\treasoning\x12\x1a\n" +
	"\bungraded\x18\a \x01(\bR\bungraded\"_\n" +
	"\x15GradeCriteriaResponse\x120\n" +
	"\bverdicts\x18\x01 \x03(\v2\x14.ai.CriterionVerdictR\bverdicts\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\";\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\xc0\x02\n" +
	"\vChatRequest\x12\x1d\n" +
	"\n" +
	"user_email\x18\x01 \x01(\tR\tuserEmail\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x19\n" +
	"\bphase_id\x18\x03 \x01(\tR\aphaseId\x12(\n" +
	"\x10active_file_path\x18\x04 \x01(\tR\x0eactiveFilePath\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12)\n" +
	"\ahistory\x18\x06 \x03(\v2\x0f.ai.ChatMessageR\ahistory\x12\x12\n" +
	"\x04mode\x18\a \x01(\tR\x04mode\x12!\n" +
	"\fcurrent_task\x18\b \x01(\tR\vcurrentTask\x122\n" +
	"\x15snapshot_phase_number\x18\t \x01(\x05R\x13snapshotPhaseNumber\"$\n" +
	"\fChatResponse\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply\"\xbf\x01\n" +
	"\x12GradeAnswerRequest\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\x12%\n" +
	"\x0ecorrect_answer\x18\x02 \x01(\tR\rcorrectAnswer\x12 \n" +
	"\vexplanation\x18\x03 \x01(\tR\vexplanation\x12#\n" +
	"\rquestion_type\x18\x04 \x01(\tR\fquestionType\x12\x1f\n" +
	"\vuser_answer\x18\x05 \x01(\tR\n" +
	"userAnswer\"4\n" +
	"\x13GradeAnswerResponse\x12\x1d\n" +
	"\n" +
	"is_correct\x18\x01 \x01(\bR\tisCorrect2\xbe\x01\n" +
	"\tAiService\x12+\n" +
	"\x04Chat\x12\x0f.ai.ChatRequest\x1a\x10.ai.ChatResponse0\x01\x12>\n" +
	"\vGradeAnswer\x12\x16.ai.GradeAnswerRequest\x1a\x17.ai.GradeAnswerResponse\x12D\n" +
	"\rGradeCriteria\x12\x18.ai.GradeCriteriaRequest\x1a\x19.ai.GradeCriteriaResponseB\x10Z\x0egateway/pkg/pbb\x06proto3"

var (
	file_ai_proto_rawDescOnce sync.Once
	file_ai_proto_rawDescData []byte
)

func file_ai_proto_rawDescGZIP() []byte {
	file_ai_proto_rawDescOnce.Do(func() {
		file_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_proto_rawDesc), len(file_ai_proto_rawDesc)))
	})
	return file_ai_proto_rawDescData
}

var file_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_ai_proto_goTypes = []any{
	(*CriterionToGrade)(nil),      // 0: ai.CriterionToGrade
	(*GradeCriteriaRequest)(nil),  // 1: ai.GradeCriteriaRequest
	(*CriterionVerdict)(nil),      // 2: ai.CriterionVerdict
	(*GradeCriteriaResponse)(nil), // 3: ai.GradeCriteriaResponse
	(*ChatMessage)(nil),           // 4: ai.ChatMessage
	(*ChatRequest)(nil),           // 5: ai.ChatRequest
	(*ChatResponse)(nil),          // 6: ai.ChatResponse
	(*GradeAnswerRequest)(nil),    // 7: ai.GradeAnswerRequest
	(*GradeAnswerResponse)(nil),   // 8: ai.GradeAnswerResponse
}
var file_ai_proto_depIdxs = []int32{
	0, // 0: ai.GradeCriteriaRequest.criteria:type_name -> ai.CriterionToGrade
	2, // 1: ai.GradeCriteriaResponse.verdicts:type_name -> ai.CriterionVerdict
	4, // 2: ai.ChatRequest.history:type_name -> ai.ChatMessage
	5, // 3: ai.AiService.Chat:input_type -> ai.ChatRequest
	7, // 4: ai.AiService.GradeAnswer:input_type -> ai.GradeAnswerRequest
	1, // 5: ai.AiService.GradeCriteria:input_type -> ai.GradeCriteriaRequest
	6, // 6: ai.AiService.Chat:output_type -> ai.ChatResponse
	8, // 7: ai.AiService.GradeAnswer:output_type -> ai.GradeAnswerResponse
	3, // 8: ai.AiService.GradeCriteria:output_type -> ai.GradeCriteriaResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_ai_proto_init() }
func file_ai_proto_init() {
	if File_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_proto_rawDesc), len(file_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_proto_goTypes,
		DependencyIndexes: file_ai_proto_depIdxs,
		MessageInfos:      file_ai_proto_msgTypes,
	}.Build()
	File_ai_proto = out.File
	file_ai_proto_goTypes = nil
	file_ai_proto_depIdxs = nil
}
