// /shared/proto/ai.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: ai.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AiService_Chat_FullMethodName               = "/ai.AiService/Chat"
	AiService_GradeAnswer_FullMethodName        = "/ai.AiService/GradeAnswer"
	AiService_GradeCriteria_FullMethodName      = "/ai.AiService/GradeCriteria"
	AiService_GenerateCheckpoint_FullMethodName = "/ai.AiService/GenerateCheckpoint"
	AiService_GradeExplanation_FullMethodName   = "/ai.AiService/GradeExplanation"
)

// AiServiceClient is the client API for AiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AiServiceClient interface {
	// Send one assistant message; the service assembles context itself
	// (user profile via UserService, active file content via FileService)
	// rather than trusting whatever the client happens to have in memory.
	// Server-streaming: each ChatResponse carries one text delta, not the
	// full reply — the stream ending signals completion.
	Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatResponse], error)
	// Grades a free-text knowledge-check answer (code_completion/debug types)
	// by judging whether it captures the correct fix/concept — not an exact
	// string match, so equivalent-but-differently-phrased answers (different
	// variable names, or an answer that states only the crucial change rather
	// than the whole surrounding snippet) are graded correct.
	GradeAnswer(ctx context.Context, in *GradeAnswerRequest, opts ...grpc.CallOption) (*GradeAnswerResponse, error)
	// Grades a phase submission one criterion at a time, each verdict carrying
	// the evidence for it.
	//
	// Deliberately not a chat call. Asking a model "does this submission meet the
	// goal?" produces a holistic opinion, and holistic opinions drift generous —
	// which is the failure that matters, because a false pass silently turns a
	// learning gate into a rubber stamp. Judging one narrow criterion at a time
	// and demanding a file, a line range, and a quote for every pass converts the
	// question from "is this good" into "point at where this is true", which a
	// model cannot answer by being agreeable.
	//
	// The caller decides the phase verdict by conjunction over these results;
	// this RPC never says whether the phase passed.
	GradeCriteria(ctx context.Context, in *GradeCriteriaRequest, opts ...grpc.CallOption) (*GradeCriteriaResponse, error)
	// Produces one "explain it back" question about work the user has already
	// completed, grounded in their actual files rather than the phase's topic in
	// the abstract — "why does your nav jump to the right section?" rather than
	// "what is an anchor link?".
	GenerateCheckpoint(ctx context.Context, in *GenerateCheckpointRequest, opts ...grpc.CallOption) (*GenerateCheckpointResponse, error)
	// Grades a free-text explanation for comprehension.
	//
	// This is the only grader in the system whose subject is the person rather
	// than the code, and it is the one an AI-era junior cannot pass by prompting:
	// the code already exists and already works, so reproducing it proves
	// nothing. Pasted code is therefore an automatic fail, not a partial credit.
	GradeExplanation(ctx context.Context, in *GradeExplanationRequest, opts ...grpc.CallOption) (*GradeExplanationResponse, error)
}

type aiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAiServiceClient(cc grpc.ClientConnInterface) AiServiceClient {
	return &aiServiceClient{cc}
}

func (c *aiServiceClient) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AiService_ServiceDesc.Streams[0], AiService_Chat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatRequest, ChatResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AiService_ChatClient = grpc.ServerStreamingClient[ChatResponse]

func (c *aiServiceClient) GradeAnswer(ctx context.Context, in *GradeAnswerRequest, opts ...grpc.CallOption) (*GradeAnswerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GradeAnswerResponse)
	err := c.cc.Invoke(ctx, AiService_GradeAnswer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiServiceClient) GradeCriteria(ctx context.Context, in *GradeCriteriaRequest, opts ...grpc.CallOption) (*GradeCriteriaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GradeCriteriaResponse)
	err := c.cc.Invoke(ctx, AiService_GradeCriteria_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiServiceClient) GenerateCheckpoint(ctx context.Context, in *GenerateCheckpointRequest, opts ...grpc.CallOption) (*GenerateCheckpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateCheckpointResponse)
	err := c.cc.Invoke(ctx, AiService_GenerateCheckpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiServiceClient) GradeExplanation(ctx context.Context, in *GradeExplanationRequest, opts ...grpc.CallOption) (*GradeExplanationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GradeExplanationResponse)
	err := c.cc.Invoke(ctx, AiService_GradeExplanation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AiServiceServer is the server API for AiService service.
// All implementations must embed UnimplementedAiServiceServer
// for forward compatibility.
type AiServiceServer interface {
	// Send one assistant message; the service assembles context itself
	// (user profile via UserService, active file content via FileService)
	// rather than trusting whatever the client happens to have in memory.
	// Server-streaming: each ChatResponse carries one text delta, not the
	// full reply — the stream ending signals completion.
	Chat(*ChatRequest, grpc.ServerStreamingServer[ChatResponse]) error
	// Grades a free-text knowledge-check answer (code_completion/debug types)
	// by judging whether it captures the correct fix/concept — not an exact
	// string match, so equivalent-but-differently-phrased answers (different
	// variable names, or an answer that states only the crucial change rather
	// than the whole surrounding snippet) are graded correct.
	GradeAnswer(context.Context, *GradeAnswerRequest) (*GradeAnswerResponse, error)
	// Grades a phase submission one criterion at a time, each verdict carrying
	// the evidence for it.
	//
	// Deliberately not a chat call. Asking a model "does this submission meet the
	// goal?" produces a holistic opinion, and holistic opinions drift generous —
	// which is the failure that matters, because a false pass silently turns a
	// learning gate into a rubber stamp. Judging one narrow criterion at a time
	// and demanding a file, a line range, and a quote for every pass converts the
	// question from "is this good" into "point at where this is true", which a
	// model cannot answer by being agreeable.
	//
	// The caller decides the phase verdict by conjunction over these results;
	// this RPC never says whether the phase passed.
	GradeCriteria(context.Context, *GradeCriteriaRequest) (*GradeCriteriaResponse, error)
	// Produces one "explain it back" question about work the user has already
	// completed, grounded in their actual files rather than the phase's topic in
	// the abstract — "why does your nav jump to the right section?" rather than
	// "what is an anchor link?".
	GenerateCheckpoint(context.Context, *GenerateCheckpointRequest) (*GenerateCheckpointResponse, error)
	// Grades a free-text explanation for comprehension.
	//
	// This is the only grader in the system whose subject is the person rather
	// than the code, and it is the one an AI-era junior cannot pass by prompting:
	// the code already exists and already works, so reproducing it proves
	// nothing. Pasted code is therefore an automatic fail, not a partial credit.
	GradeExplanation(context.Context, *GradeExplanationRequest) (*GradeExplanationResponse, error)
	mustEmbedUnimplementedAiServiceServer()
}

// UnimplementedAiServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAiServiceServer struct{}

func (UnimplementedAiServiceServer) Chat(*ChatRequest, grpc.ServerStreamingServer[ChatResponse]) error {
	return status.Error(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedAiServiceServer) GradeAnswer(context.Context, *GradeAnswerRequest) (*GradeAnswerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GradeAnswer not implemented")
}
func (UnimplementedAiServiceServer) GradeCriteria(context.Context, *GradeCriteriaRequest) (*GradeCriteriaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GradeCriteria not implemented")
}
func (UnimplementedAiServiceServer) GenerateCheckpoint(context.Context, *GenerateCheckpointRequest) (*GenerateCheckpointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateCheckpoint not implemented")
}
func (UnimplementedAiServiceServer) GradeExplanation(context.Context, *GradeExplanationRequest) (*GradeExplanationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GradeExplanation not implemented")
}
func (UnimplementedAiServiceServer) mustEmbedUnimplementedAiServiceServer() {}
func (UnimplementedAiServiceServer) testEmbeddedByValue()                   {}

// UnsafeAiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AiServiceServer will
// result in compilation errors.
type UnsafeAiServiceServer interface {
	mustEmbedUnimplementedAiServiceServer()
}

func RegisterAiServiceServer(s grpc.ServiceRegistrar, srv AiServiceServer) {
	// If the following call panics, it indicates UnimplementedAiServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AiService_ServiceDesc, srv)
}

func _AiService_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AiServiceServer).Chat(m, &grpc.GenericServerStream[ChatRequest, ChatResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AiService_ChatServer = grpc.ServerStreamingServer[ChatResponse]

func _AiService_GradeAnswer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GradeAnswerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServiceServer).GradeAnswer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiService_GradeAnswer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServiceServer).GradeAnswer(ctx, req.(*GradeAnswerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiService_GradeCriteria_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GradeCriteriaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServiceServer).GradeCriteria(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiService_GradeCriteria_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServiceServer).GradeCriteria(ctx, req.(*GradeCriteriaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiService_GenerateCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServiceServer).GenerateCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiService_GenerateCheckpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServiceServer).GenerateCheckpoint(ctx, req.(*GenerateCheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiService_GradeExplanation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GradeExplanationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServiceServer).GradeExplanation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiService_GradeExplanation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServiceServer).GradeExplanation(ctx, req.(*GradeExplanationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AiService_ServiceDesc is the grpc.ServiceDesc for AiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.AiService",
	HandlerType: (*AiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GradeAnswer",
			Handler:    _AiService_GradeAnswer_Handler,
		},
		{
			MethodName: "GradeCriteria",
			Handler:    _AiService_GradeCriteria_Handler,
		},
		{
			MethodName: "GenerateCheckpoint",
			Handler:    _AiService_GenerateCheckpoint_Handler,
		},
		{
			MethodName: "GradeExplanation",
			Handler:    _AiService_GradeExplanation_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Chat",
			Handler:       _AiService_Chat_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ai.proto",
}
