// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: entranceTest.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartTestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTestRequest) Reset() {
	*x = StartTestRequest{}
	mi := &file_entranceTest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTestRequest) ProtoMessage() {}

func (x *StartTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entranceTest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTestRequest.ProtoReflect.Descriptor instead.
func (*StartTestRequest) Descriptor() ([]byte, []int) {
	return file_entranceTest_proto_rawDescGZIP(), []int{0}
}

func (x *StartTestRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type StartTestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Questions     []*EntranceQuestionDTO `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"` // first 2 easy questions
	AttemptId     string                 `protobuf:"bytes,2,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	Round         int32                  `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTestResponse) Reset() {
	*x = StartTestResponse{}
	mi := &file_entranceTest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTestResponse) ProtoMessage() {}

func (x *StartTestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entranceTest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTestResponse.ProtoReflect.Descriptor instead.
func (*StartTestResponse) Descriptor() ([]byte, []int) {
	return file_entranceTest_proto_rawDescGZIP(), []int{1}
}

func (x *StartTestResponse) GetQuestions() []*EntranceQuestionDTO {
	if x != nil {
		return x.Questions
	}
	return nil
}

func (x *StartTestResponse) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *StartTestResponse) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

type SubmitRoundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Answers       []*AnswerDTO           `protobuf:"bytes,2,rep,name=answers,proto3" json:"answers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitRoundRequest) Reset() {
	*x = SubmitRoundRequest{}
	mi := &file_entranceTest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRoundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRoundRequest) ProtoMessage() {}

func (x *SubmitRoundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entranceTest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRoundRequest.ProtoReflect.Descriptor instead.
func (*SubmitRoundRequest) Descriptor() ([]byte, []int) {
	return file_entranceTest_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitRoundRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SubmitRoundRequest) GetAnswers() []*AnswerDTO {
	if x != nil {
		return x.Answers
	}
	return nil
}

type SubmitRoundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Done          bool                   `protobuf:"varint,1,opt,name=done,proto3" json:"done,omitempty"`
	SkillLevel    string                 `protobuf:"bytes,2,opt,name=skill_level,json=skillLevel,proto3" json:"skill_level,omitempty"`          // populated when done = true
	NextQuestions []*EntranceQuestionDTO `protobuf:"bytes,3,rep,name=next_questions,json=nextQuestions,proto3" json:"next_questions,omitempty"` // populated when done = false
	Round         int32                  `protobuf:"varint,4,opt,name=round,proto3" json:"round,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitRoundResponse) Reset() {
	*x = SubmitRoundResponse{}
	mi := &file_entranceTest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRoundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRoundResponse) ProtoMessage() {}

func (x *SubmitRoundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entranceTest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRoundResponse.ProtoReflect.Descriptor instead.
func (*SubmitRoundResponse) Descriptor() ([]byte, []int) {
	return file_entranceTest_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitRoundResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *SubmitRoundResponse) GetSkillLevel() string {
	if x != nil {
		return x.SkillLevel
	}
	return ""
}

func (x *SubmitRoundResponse) GetNextQuestions() []*EntranceQuestionDTO {
	if x != nil {
		return x.NextQuestions
	}
	return nil
}

func (x *SubmitRoundResponse) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

type EntranceQuestionDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Question      string                 `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	Options       []string               `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`
	Difficulty    string                 `protobuf:"bytes,4,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Topic         string                 `protobuf:"bytes,5,opt,name=topic,proto3" json:"topic,omitempty"` // correct_option intentionally omitted — never sent to client
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntranceQuestionDTO) Reset() {
	*x = EntranceQuestionDTO{}
	mi := &file_entranceTest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntranceQuestionDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntranceQuestionDTO) ProtoMessage() {}

func (x *EntranceQuestionDTO) ProtoReflect() protoreflect.Message {
	mi := &file_entranceTest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntranceQuestionDTO.ProtoReflect.Descriptor instead.
func (*EntranceQuestionDTO) Descriptor() ([]byte, []int) {
	return file_entranceTest_proto_rawDescGZIP(), []int{4}
}

func (x *EntranceQuestionDTO) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EntranceQuestionDTO) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *EntranceQuestionDTO) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *EntranceQuestionDTO) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *EntranceQuestionDTO) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type AnswerDTO struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	QuestionId     string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	SelectedOption int32                  `protobuf:"varint,2,opt,name=selected_option,json=selectedOption,proto3" json:"selected_option,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AnswerDTO) Reset() {
	*x = AnswerDTO{}
	mi := &file_entranceTest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerDTO) ProtoMessage() {}

func (x *AnswerDTO) ProtoReflect() protoreflect.Message {
	mi := &file_entranceTest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerDTO.ProtoReflect.Descriptor instead.
func (*AnswerDTO) Descriptor() ([]byte, []int) {
	return file_entranceTest_proto_rawDescGZIP(), []int{5}
}

func (x *AnswerDTO) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *AnswerDTO) GetSelectedOption() int32 {
	if x != nil {
		return x.SelectedOption
	}
	return 0
}

var File_entranceTest_proto protoreflect.FileDescriptor

const file_entranceTest_proto_rawDesc = "" +
	"\n" +
	"\x12entranceTest.proto\x12\fentrancetest\"(\n" +
	"\x10StartTestRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"\x89\x01\n" +
	"\x11StartTestResponse\x12?\n" +
	"\tquestions\x18\x01 \x03(\v2!.entrancetest.EntranceQuestionDTOR\tquestions\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x02 \x01(\tR\tattemptId\x12\x14\n" +
	"\x05round\x18\x03 \x01(\x05R\x05round\"]\n" +
	"\x12SubmitRoundRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x121\n" +
	"\aanswers\x18\x02 \x03(\v2\x17.entrancetest.AnswerDTOR\aanswers\"\xaa\x01\n" +
	"\x13SubmitRoundResponse\x12\x12\n" +
	"\x04done\x18\x01 \x01(\bR\x04done\x12\x1f\n" +
	"\vskill_level\x18\x02 \x01(\tR\n" +
	"skillLevel\x12H\n" +
	"\x0enext_questions\x18\x03 \x03(\v2!.entrancetest.EntranceQuestionDTOR\rnextQuestions\x12\x14\n" +
	"\x05round\x18\x04 \x01(\x05R\x05round\"\x91\x01\n" +
	"\x13EntranceQuestionDTO\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bquestion\x18\x02 \x01(\tR\bquestion\x12\x18\n" +
	"\aoptions\x18\x03 \x03(\tR\aoptions\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x04 \x01(\tR\n" +
	"difficulty\x12\x14\n" +
	"\x05topic\x18\x05 \x01(\tR\x05topic\"U\n" +
	"\tAnswerDTO\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\x12'\n" +
	"\x0fselected_option\x18\x02 \x01(\x05R\x0eselectedOption2\xb7\x01\n" +
	"\x13EntranceTestService\x12L\n" +
	"\tStartTest\x12\x1e.entrancetest.StartTestRequest\x1a\x1f.entrancetest.StartTestResponse\x12R\n" +
	"\vSubmitRound\x12 .entrancetest.SubmitRoundRequest\x1a!.entrancetest.SubmitRoundResponseB\x10Z\x0egateway/pkg/pbb\x06proto3"

var (
	file_entranceTest_proto_rawDescOnce sync.Once
	file_entranceTest_proto_rawDescData []byte
)

func file_entranceTest_proto_rawDescGZIP() []byte {
	file_entranceTest_proto_rawDescOnce.Do(func() {
		file_entranceTest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entranceTest_proto_rawDesc), len(file_entranceTest_proto_rawDesc)))
	})
	return file_entranceTest_proto_rawDescData
}

var file_entranceTest_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_entranceTest_proto_goTypes = []any{
	(*StartTestRequest)(nil),    // 0: entrancetest.StartTestRequest
	(*StartTestResponse)(nil),   // 1: entrancetest.StartTestResponse
	(*SubmitRoundRequest)(nil),  // 2: entrancetest.SubmitRoundRequest
	(*SubmitRoundResponse)(nil), // 3: entrancetest.SubmitRoundResponse
	(*EntranceQuestionDTO)(nil), // 4: entrancetest.EntranceQuestionDTO
	(*AnswerDTO)(nil),           // 5: entrancetest.AnswerDTO
}
var file_entranceTest_proto_depIdxs = []int32{
	4, // 0: entrancetest.StartTestResponse.questions:type_name -> entrancetest.EntranceQuestionDTO
	5, // 1: entrancetest.SubmitRoundRequest.answers:type_name -> entrancetest.AnswerDTO
	4, // 2: entrancetest.SubmitRoundResponse.next_questions:type_name -> entrancetest.EntranceQuestionDTO
	0, // 3: entrancetest.EntranceTestService.StartTest:input_type -> entrancetest.StartTestRequest
	2, // 4: entrancetest.EntranceTestService.SubmitRound:input_type -> entrancetest.SubmitRoundRequest
	1, // 5: entrancetest.EntranceTestService.StartTest:output_type -> entrancetest.StartTestResponse
	3, // 6: entrancetest.EntranceTestService.SubmitRound:output_type -> entrancetest.SubmitRoundResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_entranceTest_proto_init() }
func file_entranceTest_proto_init() {
	if File_entranceTest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entranceTest_proto_rawDesc), len(file_entranceTest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_entranceTest_proto_goTypes,
		DependencyIndexes: file_entranceTest_proto_depIdxs,
		MessageInfos:      file_entranceTest_proto_msgTypes,
	}.Build()
	File_entranceTest_proto = out.File
	file_entranceTest_proto_goTypes = nil
	file_entranceTest_proto_depIdxs = nil
}
