// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: entranceTest.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EntranceTestService_StartTest_FullMethodName   = "/entrancetest.EntranceTestService/StartTest"
	EntranceTestService_SubmitRound_FullMethodName = "/entrancetest.EntranceTestService/SubmitRound"
)

// EntranceTestServiceClient is the client API for EntranceTestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EntranceTestServiceClient interface {
	StartTest(ctx context.Context, in *StartTestRequest, opts ...grpc.CallOption) (*StartTestResponse, error)
	SubmitRound(ctx context.Context, in *SubmitRoundRequest, opts ...grpc.CallOption) (*SubmitRoundResponse, error)
}

type entranceTestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEntranceTestServiceClient(cc grpc.ClientConnInterface) EntranceTestServiceClient {
	return &entranceTestServiceClient{cc}
}

func (c *entranceTestServiceClient) StartTest(ctx context.Context, in *StartTestRequest, opts ...grpc.CallOption) (*StartTestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartTestResponse)
	err := c.cc.Invoke(ctx, EntranceTestService_StartTest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entranceTestServiceClient) SubmitRound(ctx context.Context, in *SubmitRoundRequest, opts ...grpc.CallOption) (*SubmitRoundResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitRoundResponse)
	err := c.cc.Invoke(ctx, EntranceTestService_SubmitRound_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EntranceTestServiceServer is the server API for EntranceTestService service.
// All implementations must embed UnimplementedEntranceTestServiceServer
// for forward compatibility.
type EntranceTestServiceServer interface {
	StartTest(context.Context, *StartTestRequest) (*StartTestResponse, error)
	SubmitRound(context.Context, *SubmitRoundRequest) (*SubmitRoundResponse, error)
	mustEmbedUnimplementedEntranceTestServiceServer()
}

// UnimplementedEntranceTestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEntranceTestServiceServer struct{}

func (UnimplementedEntranceTestServiceServer) StartTest(context.Context, *StartTestRequest) (*StartTestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartTest not implemented")
}
func (UnimplementedEntranceTestServiceServer) SubmitRound(context.Context, *SubmitRoundRequest) (*SubmitRoundResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitRound not implemented")
}
func (UnimplementedEntranceTestServiceServer) mustEmbedUnimplementedEntranceTestServiceServer() {}
func (UnimplementedEntranceTestServiceServer) testEmbeddedByValue()                             {}

// UnsafeEntranceTestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EntranceTestServiceServer will
// result in compilation errors.
type UnsafeEntranceTestServiceServer interface {
	mustEmbedUnimplementedEntranceTestServiceServer()
}

func RegisterEntranceTestServiceServer(s grpc.ServiceRegistrar, srv EntranceTestServiceServer) {
	// If the following call panics, it indicates UnimplementedEntranceTestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EntranceTestService_ServiceDesc, srv)
}

func _EntranceTestService_StartTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartTestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntranceTestServiceServer).StartTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntranceTestService_StartTest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntranceTestServiceServer).StartTest(ctx, req.(*StartTestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntranceTestService_SubmitRound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitRoundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntranceTestServiceServer).SubmitRound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntranceTestService_SubmitRound_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntranceTestServiceServer).SubmitRound(ctx, req.(*SubmitRoundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EntranceTestService_ServiceDesc is the grpc.ServiceDesc for EntranceTestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EntranceTestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "entrancetest.EntranceTestService",
	HandlerType: (*EntranceTestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartTest",
			Handler:    _EntranceTestService_StartTest_Handler,
		},
		{
			MethodName: "SubmitRound",
			Handler:    _EntranceTestService_SubmitRound_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "entranceTest.proto",
}
