// /shared/proto/knowledgeCheck.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: knowledgeCheck.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KnowledgeCheckService_GetPhaseKnowledgeChecks_FullMethodName = "/knowledgeCheck.KnowledgeCheckService/GetPhaseKnowledgeChecks"
	KnowledgeCheckService_SubmitAnswer_FullMethodName            = "/knowledgeCheck.KnowledgeCheckService/SubmitAnswer"
	KnowledgeCheckService_GetQuizAverages_FullMethodName         = "/knowledgeCheck.KnowledgeCheckService/GetQuizAverages"
)

// KnowledgeCheckServiceClient is the client API for KnowledgeCheckService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KnowledgeCheckServiceClient interface {
	// Fetch all knowledge checks for a phase, with the user's attempt status
	GetPhaseKnowledgeChecks(ctx context.Context, in *GetPhaseKnowledgeChecksRequest, opts ...grpc.CallOption) (*GetPhaseKnowledgeChecksResponse, error)
	// Submit an answer for a single knowledge check (graded server-side)
	SubmitAnswer(ctx context.Context, in *SubmitAnswerRequest, opts ...grpc.CallOption) (*SubmitAnswerResponse, error)
	// Fetch the user's quiz average (% correct) per skill level, for progression gating
	GetQuizAverages(ctx context.Context, in *GetQuizAveragesRequest, opts ...grpc.CallOption) (*GetQuizAveragesResponse, error)
}

type knowledgeCheckServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKnowledgeCheckServiceClient(cc grpc.ClientConnInterface) KnowledgeCheckServiceClient {
	return &knowledgeCheckServiceClient{cc}
}

func (c *knowledgeCheckServiceClient) GetPhaseKnowledgeChecks(ctx context.Context, in *GetPhaseKnowledgeChecksRequest, opts ...grpc.CallOption) (*GetPhaseKnowledgeChecksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPhaseKnowledgeChecksResponse)
	err := c.cc.Invoke(ctx, KnowledgeCheckService_GetPhaseKnowledgeChecks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeCheckServiceClient) SubmitAnswer(ctx context.Context, in *SubmitAnswerRequest, opts ...grpc.CallOption) (*SubmitAnswerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitAnswerResponse)
	err := c.cc.Invoke(ctx, KnowledgeCheckService_SubmitAnswer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeCheckServiceClient) GetQuizAverages(ctx context.Context, in *GetQuizAveragesRequest, opts ...grpc.CallOption) (*GetQuizAveragesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetQuizAveragesResponse)
	err := c.cc.Invoke(ctx, KnowledgeCheckService_GetQuizAverages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KnowledgeCheckServiceServer is the server API for KnowledgeCheckService service.
// All implementations must embed UnimplementedKnowledgeCheckServiceServer
// for forward compatibility.
type KnowledgeCheckServiceServer interface {
	// Fetch all knowledge checks for a phase, with the user's attempt status
	GetPhaseKnowledgeChecks(context.Context, *GetPhaseKnowledgeChecksRequest) (*GetPhaseKnowledgeChecksResponse, error)
	// Submit an answer for a single knowledge check (graded server-side)
	SubmitAnswer(context.Context, *SubmitAnswerRequest) (*SubmitAnswerResponse, error)
	// Fetch the user's quiz average (% correct) per skill level, for progression gating
	GetQuizAverages(context.Context, *GetQuizAveragesRequest) (*GetQuizAveragesResponse, error)
	mustEmbedUnimplementedKnowledgeCheckServiceServer()
}

// UnimplementedKnowledgeCheckServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKnowledgeCheckServiceServer struct{}

func (UnimplementedKnowledgeCheckServiceServer) GetPhaseKnowledgeChecks(context.Context, *GetPhaseKnowledgeChecksRequest) (*GetPhaseKnowledgeChecksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPhaseKnowledgeChecks not implemented")
}
func (UnimplementedKnowledgeCheckServiceServer) SubmitAnswer(context.Context, *SubmitAnswerRequest) (*SubmitAnswerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitAnswer not implemented")
}
func (UnimplementedKnowledgeCheckServiceServer) GetQuizAverages(context.Context, *GetQuizAveragesRequest) (*GetQuizAveragesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetQuizAverages not implemented")
}
func (UnimplementedKnowledgeCheckServiceServer) mustEmbedUnimplementedKnowledgeCheckServiceServer() {}
func (UnimplementedKnowledgeCheckServiceServer) testEmbeddedByValue()                               {}

// UnsafeKnowledgeCheckServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KnowledgeCheckServiceServer will
// result in compilation errors.
type UnsafeKnowledgeCheckServiceServer interface {
	mustEmbedUnimplementedKnowledgeCheckServiceServer()
}

func RegisterKnowledgeCheckServiceServer(s grpc.ServiceRegistrar, srv KnowledgeCheckServiceServer) {
	// If the following call panics, it indicates UnimplementedKnowledgeCheckServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KnowledgeCheckService_ServiceDesc, srv)
}

func _KnowledgeCheckService_GetPhaseKnowledgeChecks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPhaseKnowledgeChecksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeCheckServiceServer).GetPhaseKnowledgeChecks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeCheckService_GetPhaseKnowledgeChecks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeCheckServiceServer).GetPhaseKnowledgeChecks(ctx, req.(*GetPhaseKnowledgeChecksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeCheckService_SubmitAnswer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitAnswerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeCheckServiceServer).SubmitAnswer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeCheckService_SubmitAnswer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeCheckServiceServer).SubmitAnswer(ctx, req.(*SubmitAnswerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeCheckService_GetQuizAverages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQuizAveragesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeCheckServiceServer).GetQuizAverages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeCheckService_GetQuizAverages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeCheckServiceServer).GetQuizAverages(ctx, req.(*GetQuizAveragesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KnowledgeCheckService_ServiceDesc is the grpc.ServiceDesc for KnowledgeCheckService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KnowledgeCheckService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "knowledgeCheck.KnowledgeCheckService",
	HandlerType: (*KnowledgeCheckServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPhaseKnowledgeChecks",
			Handler:    _KnowledgeCheckService_GetPhaseKnowledgeChecks_Handler,
		},
		{
			MethodName: "SubmitAnswer",
			Handler:    _KnowledgeCheckService_SubmitAnswer_Handler,
		},
		{
			MethodName: "GetQuizAverages",
			Handler:    _KnowledgeCheckService_GetQuizAverages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "knowledgeCheck.proto",
}
