// /shared/proto/resourceProgress.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: resourceProgress.proto

package pb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ResourceProgressService_GetPhaseResources_FullMethodName = "/resourceProgress.ResourceProgressService/GetPhaseResources"
	ResourceProgressService_MarkCompleted_FullMethodName     = "/resourceProgress.ResourceProgressService/MarkCompleted"
	ResourceProgressService_GetProgress_FullMethodName       = "/resourceProgress.ResourceProgressService/GetProgress"
)

// ResourceProgressServiceClient is the client API for ResourceProgressService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ResourceProgressServiceClient interface {
	// Fetch all resources for a phase, with per-user completion status
	GetPhaseResources(ctx context.Context, in *GetPhaseResourcesRequest, opts ...grpc.CallOption) (*GetPhaseResourcesResponse, error)
	// Mark or unmark a single resource as completed
	MarkCompleted(ctx context.Context, in *MarkCompletedRequest, opts ...grpc.CallOption) (*MarkCompletedResponse, error)
	// Fetch all completion records for a user+project (lightweight, all phases)
	GetProgress(ctx context.Context, in *GetProgressRequest, opts ...grpc.CallOption) (*GetProgressResponse, error)
}

type resourceProgressServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewResourceProgressServiceClient(cc grpc.ClientConnInterface) ResourceProgressServiceClient {
	return &resourceProgressServiceClient{cc}
}

func (c *resourceProgressServiceClient) GetPhaseResources(ctx context.Context, in *GetPhaseResourcesRequest, opts ...grpc.CallOption) (*GetPhaseResourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPhaseResourcesResponse)
	err := c.cc.Invoke(ctx, ResourceProgressService_GetPhaseResources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceProgressServiceClient) MarkCompleted(ctx context.Context, in *MarkCompletedRequest, opts ...grpc.CallOption) (*MarkCompletedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkCompletedResponse)
	err := c.cc.Invoke(ctx, ResourceProgressService_MarkCompleted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceProgressServiceClient) GetProgress(ctx context.Context, in *GetProgressRequest, opts ...grpc.CallOption) (*GetProgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProgressResponse)
	err := c.cc.Invoke(ctx, ResourceProgressService_GetProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResourceProgressServiceServer is the server API for ResourceProgressService service.
// All implementations must embed UnimplementedResourceProgressServiceServer
// for forward compatibility.
type ResourceProgressServiceServer interface {
	// Fetch all resources for a phase, with per-user completion status
	GetPhaseResources(context.Context, *GetPhaseResourcesRequest) (*GetPhaseResourcesResponse, error)
	// Mark or unmark a single resource as completed
	MarkCompleted(context.Context, *MarkCompletedRequest) (*MarkCompletedResponse, error)
	// Fetch all completion records for a user+project (lightweight, all phases)
	GetProgress(context.Context, *GetProgressRequest) (*GetProgressResponse, error)
	mustEmbedUnimplementedResourceProgressServiceServer()
}

// UnimplementedResourceProgressServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedResourceProgressServiceServer struct{}

func (UnimplementedResourceProgressServiceServer) GetPhaseResources(context.Context, *GetPhaseResourcesRequest) (*GetPhaseResourcesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPhaseResources not implemented")
}
func (UnimplementedResourceProgressServiceServer) MarkCompleted(context.Context, *MarkCompletedRequest) (*MarkCompletedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkCompleted not implemented")
}
func (UnimplementedResourceProgressServiceServer) GetProgress(context.Context, *GetProgressRequest) (*GetProgressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProgress not implemented")
}
func (UnimplementedResourceProgressServiceServer) mustEmbedUnimplementedResourceProgressServiceServer() {
}
func (UnimplementedResourceProgressServiceServer) testEmbeddedByValue() {}

// UnsafeResourceProgressServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResourceProgressServiceServer will
// result in compilation errors.
type UnsafeResourceProgressServiceServer interface {
	mustEmbedUnimplementedResourceProgressServiceServer()
}

func RegisterResourceProgressServiceServer(s grpc.ServiceRegistrar, srv ResourceProgressServiceServer) {
	// If the following call panics, it indicates UnimplementedResourceProgressServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ResourceProgressService_ServiceDesc, srv)
}

func _ResourceProgressService_GetPhaseResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPhaseResourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceProgressServiceServer).GetPhaseResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceProgressService_GetPhaseResources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceProgressServiceServer).GetPhaseResources(ctx, req.(*GetPhaseResourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceProgressService_MarkCompleted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkCompletedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceProgressServiceServer).MarkCompleted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceProgressService_MarkCompleted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceProgressServiceServer).MarkCompleted(ctx, req.(*MarkCompletedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceProgressService_GetProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceProgressServiceServer).GetProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceProgressService_GetProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceProgressServiceServer).GetProgress(ctx, req.(*GetProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ResourceProgressService_ServiceDesc is the grpc.ServiceDesc for ResourceProgressService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ResourceProgressService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "resourceProgress.ResourceProgressService",
	HandlerType: (*ResourceProgressServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPhaseResources",
			Handler:    _ResourceProgressService_GetPhaseResources_Handler,
		},
		{
			MethodName: "MarkCompleted",
			Handler:    _ResourceProgressService_MarkCompleted_Handler,
		},
		{
			MethodName: "GetProgress",
			Handler:    _ResourceProgressService_GetProgress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "resourceProgress.proto",
}
