// /shared/proto/resourceProgress.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: resourceProgress.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPhaseResourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhaseId       string                 `protobuf:"bytes,1,opt,name=phase_id,json=phaseId,proto3" json:"phase_id,omitempty"`
	UserEmail     string                 `protobuf:"bytes,2,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	ProjectId     string                 `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPhaseResourcesRequest) Reset() {
	*x = GetPhaseResourcesRequest{}
	mi := &file_resourceProgress_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPhaseResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPhaseResourcesRequest) ProtoMessage() {}

func (x *GetPhaseResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resourceProgress_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPhaseResourcesRequest.ProtoReflect.Descriptor instead.
func (*GetPhaseResourcesRequest) Descriptor() ([]byte, []int) {
	return file_resourceProgress_proto_rawDescGZIP(), []int{0}
}

func (x *GetPhaseResourcesRequest) GetPhaseId() string {
	if x != nil {
		return x.PhaseId
	}
	return ""
}

func (x *GetPhaseResourcesRequest) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *GetPhaseResourcesRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type ResourceItem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PhaseId         string                 `protobuf:"bytes,2,opt,name=phase_id,json=phaseId,proto3" json:"phase_id,omitempty"`
	Type            string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // "video" | "article" | "docs" | etc.
	Title           string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Url             string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	DurationMinutes int32                  `protobuf:"varint,6,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	Provider        string                 `protobuf:"bytes,7,opt,name=provider,proto3" json:"provider,omitempty"`
	QualityScore    float32                `protobuf:"fixed32,8,opt,name=quality_score,json=qualityScore,proto3" json:"quality_score,omitempty"`
	Completed       bool                   `protobuf:"varint,9,opt,name=completed,proto3" json:"completed,omitempty"`                        // per-user completion, injected server-side
	CompletedAt     string                 `protobuf:"bytes,10,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"` // ISO string, empty if not completed
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResourceItem) Reset() {
	*x = ResourceItem{}
	mi := &file_resourceProgress_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceItem) ProtoMessage() {}

func (x *ResourceItem) ProtoReflect() protoreflect.Message {
	mi := &file_resourceProgress_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceItem.ProtoReflect.Descriptor instead.
func (*ResourceItem) Descriptor() ([]byte, []int) {
	return file_resourceProgress_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResourceItem) GetPhaseId() string {
	if x != nil {
		return x.PhaseId
	}
	return ""
}

func (x *ResourceItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResourceItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ResourceItem) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ResourceItem) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *ResourceItem) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ResourceItem) GetQualityScore() float32 {
	if x != nil {
		return x.QualityScore
	}
	return 0
}

func (x *ResourceItem) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *ResourceItem) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

type GetPhaseResourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resources     []*ResourceItem        `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPhaseResourcesResponse) Reset() {
	*x = GetPhaseResourcesResponse{}
	mi := &file_resourceProgress_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPhaseResourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPhaseResourcesResponse) ProtoMessage() {}

func (x *GetPhaseResourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resourceProgress_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPhaseResourcesResponse.ProtoReflect.Descriptor instead.
func (*GetPhaseResourcesResponse) Descriptor() ([]byte, []int) {
	return file_resourceProgress_proto_rawDescGZIP(), []int{2}
}

func (x *GetPhaseResourcesResponse) GetResources() []*ResourceItem {
	if x != nil {
		return x.Resources
	}
	return nil
}

type MarkCompletedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	UserEmail     string                 `protobuf:"bytes,2,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	ProjectId     string                 `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Completed     bool                   `protobuf:"varint,4,opt,name=completed,proto3" json:"completed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkCompletedRequest) Reset() {
	*x = MarkCompletedRequest{}
	mi := &file_resourceProgress_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkCompletedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkCompletedRequest) ProtoMessage() {}

func (x *MarkCompletedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resourceProgress_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkCompletedRequest.ProtoReflect.Descriptor instead.
func (*MarkCompletedRequest) Descriptor() ([]byte, []int) {
	return file_resourceProgress_proto_rawDescGZIP(), []int{3}
}

func (x *MarkCompletedRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *MarkCompletedRequest) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *MarkCompletedRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *MarkCompletedRequest) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

type MarkCompletedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkCompletedResponse) Reset() {
	*x = MarkCompletedResponse{}
	mi := &file_resourceProgress_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkCompletedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkCompletedResponse) ProtoMessage() {}

func (x *MarkCompletedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resourceProgress_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkCompletedResponse.ProtoReflect.Descriptor instead.
func (*MarkCompletedResponse) Descriptor() ([]byte, []int) {
	return file_resourceProgress_proto_rawDescGZIP(), []int{4}
}

func (x *MarkCompletedResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserEmail     string                 `protobuf:"bytes,1,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProgressRequest) Reset() {
	*x = GetProgressRequest{}
	mi := &file_resourceProgress_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgressRequest) ProtoMessage() {}

func (x *GetProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resourceProgress_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgressRequest.ProtoReflect.Descriptor instead.
func (*GetProgressRequest) Descriptor() ([]byte, []int) {
	return file_resourceProgress_proto_rawDescGZIP(), []int{5}
}

func (x *GetProgressRequest) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *GetProgressRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type ProgressEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Completed     bool                   `protobuf:"varint,2,opt,name=completed,proto3" json:"completed,omitempty"`
	CompletedAt   string                 `protobuf:"bytes,3,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"` // ISO string, empty if not completed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressEntry) Reset() {
	*x = ProgressEntry{}
	mi := &file_resourceProgress_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressEntry) ProtoMessage() {}

func (x *ProgressEntry) ProtoReflect() protoreflect.Message {
	mi := &file_resourceProgress_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressEntry.ProtoReflect.Descriptor instead.
func (*ProgressEntry) Descriptor() ([]byte, []int) {
	return file_resourceProgress_proto_rawDescGZIP(), []int{6}
}

func (x *ProgressEntry) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *ProgressEntry) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *ProgressEntry) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

type GetProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*ProgressEntry       `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProgressResponse) Reset() {
	*x = GetProgressResponse{}
	mi := &file_resourceProgress_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgressResponse) ProtoMessage() {}

func (x *GetProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resourceProgress_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgressResponse.ProtoReflect.Descriptor instead.
func (*GetProgressResponse) Descriptor() ([]byte, []int) {
	return file_resourceProgress_proto_rawDescGZIP(), []int{7}
}

func (x *GetProgressResponse) GetEntries() []*ProgressEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_resourceProgress_proto protoreflect.FileDescriptor

const file_resourceProgress_proto_rawDesc = "" +
	"\n" +
	"\x16resourceProgress.proto\x12\x10resourceProgress\"s\n" +
	"\x18GetPhaseResourcesRequest\x12\x19\n" +
	"\bphase_id\x18\x01 \x01(\tR\aphaseId\x12\x1d\n" +
	"\n" +
	"user_email\x18\x02 \x01(\tR\tuserEmail\x12\x1d\n" +
	"\n" +
	"project_id\x18\x03 \x01(\tR\tprojectId\"\xa2\x02\n" +
	"\fResourceItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bphase_id\x18\x02 \x01(\tR\aphaseId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12)\n" +
	"\x10duration_minutes\x18\x06 \x01(\x05R\x0fdurationMinutes\x12\x1a\n" +
	"\bprovider\x18\a \x01(\tR\bprovider\x12#\n" +
	"\rquality_score\x18\b \x01(\x02R\fqualityScore\x12\x1c\n" +
	"\tcompleted\x18\t \x01(\bR\tcompleted\x12!\n" +
	"\fcompleted_at\x18\n" +
	" \x01(\tR\vcompletedAt\"Y\n" +
	"\x19GetPhaseResourcesResponse\x12<\n" +
	"\tresources\x18\x01 \x03(\v2\x1e.resourceProgress.ResourceItemR\tresources\"\x93\x01\n" +
	"\x14MarkCompletedRequest\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12\x1d\n" +
	"\n" +
	"user_email\x18\x02 \x01(\tR\tuserEmail\x12\x1d\n" +
	"\n" +
	"project_id\x18\x03 \x01(\tR\tprojectId\x12\x1c\n" +
	"\tcompleted\x18\x04 \x01(\bR\tcompleted\"1\n" +
	"\x15MarkCompletedResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"R\n" +
	"\x12GetProgressRequest\x12\x1d\n" +
	"\n" +
	"user_email\x18\x01 \x01(\tR\tuserEmail\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\"q\n" +
	"\rProgressEntry\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12\x1c\n" +
	"\tcompleted\x18\x02 \x01(\bR\tcompleted\x12!\n" +
	"\fcompleted_at\x18\x03 \x01(\tR\vcompletedAt\"P\n" +
	"\x13GetProgressResponse\x129\n" +
	"\aentries\x18\x01 \x03(\v2\x1f.resourceProgress.ProgressEntryR\aentries2\xc5\x02\n" +
	"\x17ResourceProgressService\x12l\n" +
	"\x11GetPhaseResources\x12*.resourceProgress.GetPhaseResourcesRequest\x1a+.resourceProgress.GetPhaseResourcesResponse\x12`\n" +
	"\rMarkCompleted\x12&.resourceProgress.MarkCompletedRequest\x1a'.resourceProgress.MarkCompletedResponse\x12Z\n" +
	"\vGetProgress\x12$.resourceProgress.GetProgressRequest\x1a%.resourceProgress.GetProgressResponseB\x10Z\x0egateway/pkg/pbb\x06proto3"

var (
	file_resourceProgress_proto_rawDescOnce sync.Once
	file_resourceProgress_proto_rawDescData []byte
)

func file_resourceProgress_proto_rawDescGZIP() []byte {
	file_resourceProgress_proto_rawDescOnce.Do(func() {
		file_resourceProgress_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resourceProgress_proto_rawDesc), len(file_resourceProgress_proto_rawDesc)))
	})
	return file_resourceProgress_proto_rawDescData
}

var file_resourceProgress_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_resourceProgress_proto_goTypes = []any{
	(*GetPhaseResourcesRequest)(nil),  // 0: resourceProgress.GetPhaseResourcesRequest
	(*ResourceItem)(nil),              // 1: resourceProgress.ResourceItem
	(*GetPhaseResourcesResponse)(nil), // 2: resourceProgress.GetPhaseResourcesResponse
	(*MarkCompletedRequest)(nil),      // 3: resourceProgress.MarkCompletedRequest
	(*MarkCompletedResponse)(nil),     // 4: resourceProgress.MarkCompletedResponse
	(*GetProgressRequest)(nil),        // 5: resourceProgress.GetProgressRequest
	(*ProgressEntry)(nil),             // 6: resourceProgress.ProgressEntry
	(*GetProgressResponse)(nil),       // 7: resourceProgress.GetProgressResponse
}
var file_resourceProgress_proto_depIdxs = []int32{
	1, // 0: resourceProgress.GetPhaseResourcesResponse.resources:type_name -> resourceProgress.ResourceItem
	6, // 1: resourceProgress.GetProgressResponse.entries:type_name -> resourceProgress.ProgressEntry
	0, // 2: resourceProgress.ResourceProgressService.GetPhaseResources:input_type -> resourceProgress.GetPhaseResourcesRequest
	3, // 3: resourceProgress.ResourceProgressService.MarkCompleted:input_type -> resourceProgress.MarkCompletedRequest
	5, // 4: resourceProgress.ResourceProgressService.GetProgress:input_type -> resourceProgress.GetProgressRequest
	2, // 5: resourceProgress.ResourceProgressService.GetPhaseResources:output_type -> resourceProgress.GetPhaseResourcesResponse
	4, // 6: resourceProgress.ResourceProgressService.MarkCompleted:output_type -> resourceProgress.MarkCompletedResponse
	7, // 7: resourceProgress.ResourceProgressService.GetProgress:output_type -> resourceProgress.GetProgressResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_resourceProgress_proto_init() }
func file_resourceProgress_proto_init() {
	if File_resourceProgress_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resourceProgress_proto_rawDesc), len(file_resourceProgress_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_resourceProgress_proto_goTypes,
		DependencyIndexes: file_resourceProgress_proto_depIdxs,
		MessageInfos:      file_resourceProgress_proto_msgTypes,
	}.Build()
	File_resourceProgress_proto = out.File
	file_resourceProgress_proto_goTypes = nil
	file_resourceProgress_proto_depIdxs = nil
}
