// /shared/proto/userProject.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: userProject.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CurrentPhase  int32                  `protobuf:"varint,4,opt,name=current_phase,json=currentPhase,proto3" json:"current_phase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserProjectRequest) Reset() {
	*x = CreateUserProjectRequest{}
	mi := &file_userProject_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserProjectRequest) ProtoMessage() {}

func (x *CreateUserProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userProject_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserProjectRequest.ProtoReflect.Descriptor instead.
func (*CreateUserProjectRequest) Descriptor() ([]byte, []int) {
	return file_userProject_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserProjectRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateUserProjectRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserProjectRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateUserProjectRequest) GetCurrentPhase() int32 {
	if x != nil {
		return x.CurrentPhase
	}
	return 0
}

type CreateUserProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserProjectResponse) Reset() {
	*x = CreateUserProjectResponse{}
	mi := &file_userProject_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserProjectResponse) ProtoMessage() {}

func (x *CreateUserProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userProject_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserProjectResponse.ProtoReflect.Descriptor instead.
func (*CreateUserProjectResponse) Descriptor() ([]byte, []int) {
	return file_userProject_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserProjectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetUserProjectByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProjectByIdRequest) Reset() {
	*x = GetUserProjectByIdRequest{}
	mi := &file_userProject_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProjectByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProjectByIdRequest) ProtoMessage() {}

func (x *GetUserProjectByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userProject_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProjectByIdRequest.ProtoReflect.Descriptor instead.
func (*GetUserProjectByIdRequest) Descriptor() ([]byte, []int) {
	return file_userProject_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserProjectByIdRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type GetUserProjectByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserProject   *UserProject           `protobuf:"bytes,1,opt,name=user_project,json=userProject,proto3" json:"user_project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProjectByIdResponse) Reset() {
	*x = GetUserProjectByIdResponse{}
	mi := &file_userProject_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProjectByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProjectByIdResponse) ProtoMessage() {}

func (x *GetUserProjectByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userProject_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProjectByIdResponse.ProtoReflect.Descriptor instead.
func (*GetUserProjectByIdResponse) Descriptor() ([]byte, []int) {
	return file_userProject_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserProjectByIdResponse) GetUserProject() *UserProject {
	if x != nil {
		return x.UserProject
	}
	return nil
}

type GetAllUserProjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllUserProjectsRequest) Reset() {
	*x = GetAllUserProjectsRequest{}
	mi := &file_userProject_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllUserProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUserProjectsRequest) ProtoMessage() {}

func (x *GetAllUserProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userProject_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUserProjectsRequest.ProtoReflect.Descriptor instead.
func (*GetAllUserProjectsRequest) Descriptor() ([]byte, []int) {
	return file_userProject_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllUserProjectsRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetAllUserProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserProjects  []*UserProject         `protobuf:"bytes,1,rep,name=user_projects,json=userProjects,proto3" json:"user_projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllUserProjectsResponse) Reset() {
	*x = GetAllUserProjectsResponse{}
	mi := &file_userProject_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllUserProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUserProjectsResponse) ProtoMessage() {}

func (x *GetAllUserProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userProject_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUserProjectsResponse.ProtoReflect.Descriptor instead.
func (*GetAllUserProjectsResponse) Descriptor() ([]byte, []int) {
	return file_userProject_proto_rawDescGZIP(), []int{5}
}

func (x *GetAllUserProjectsResponse) GetUserProjects() []*UserProject {
	if x != nil {
		return x.UserProjects
	}
	return nil
}

type UserProject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CurrentPhase  int32                  `protobuf:"varint,4,opt,name=current_phase,json=currentPhase,proto3" json:"current_phase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProject) Reset() {
	*x = UserProject{}
	mi := &file_userProject_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProject) ProtoMessage() {}

func (x *UserProject) ProtoReflect() protoreflect.Message {
	mi := &file_userProject_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProject.ProtoReflect.Descriptor instead.
func (*UserProject) Descriptor() ([]byte, []int) {
	return file_userProject_proto_rawDescGZIP(), []int{6}
}

func (x *UserProject) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *UserProject) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserProject) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UserProject) GetCurrentPhase() int32 {
	if x != nil {
		return x.CurrentPhase
	}
	return 0
}

type GetUserProjectsByStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProjectsByStatusRequest) Reset() {
	*x = GetUserProjectsByStatusRequest{}
	mi := &file_userProject_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProjectsByStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProjectsByStatusRequest) ProtoMessage() {}

func (x *GetUserProjectsByStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userProject_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProjectsByStatusRequest.ProtoReflect.Descriptor instead.
func (*GetUserProjectsByStatusRequest) Descriptor() ([]byte, []int) {
	return file_userProject_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserProjectsByStatusRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetUserProjectsByStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetUserProjectsByStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserProjects  []*UserProject         `protobuf:"bytes,1,rep,name=user_projects,json=userProjects,proto3" json:"user_projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProjectsByStatusResponse) Reset() {
	*x = GetUserProjectsByStatusResponse{}
	mi := &file_userProject_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProjectsByStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProjectsByStatusResponse) ProtoMessage() {}

func (x *GetUserProjectsByStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userProject_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProjectsByStatusResponse.ProtoReflect.Descriptor instead.
func (*GetUserProjectsByStatusResponse) Descriptor() ([]byte, []int) {
	return file_userProject_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserProjectsByStatusResponse) GetUserProjects() []*UserProject {
	if x != nil {
		return x.UserProjects
	}
	return nil
}

var File_userProject_proto protoreflect.FileDescriptor

const file_userProject_proto_rawDesc = "" +
	"\n" +
	"\x11userProject.proto\x12\vuserProject\"\x8c\x01\n" +
	"\x18CreateUserProjectRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12#\n" +
	"\rcurrent_phase\x18\x04 \x01(\x05R\fcurrentPhase\"5\n" +
	"\x19CreateUserProjectResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\":\n" +
	"\x19GetUserProjectByIdRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"Y\n" +
	"\x1aGetUserProjectByIdResponse\x12;\n" +
	"\fuser_project\x18\x01 \x01(\v2\x18.userProject.UserProjectR\vuserProject\"1\n" +
	"\x19GetAllUserProjectsRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"[\n" +
	"\x1aGetAllUserProjectsResponse\x12=\n" +
	"\ruser_projects\x18\x01 \x03(\v2\x18.userProject.UserProjectR\fuserProjects\"\x7f\n" +
	"\vUserProject\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12#\n" +
	"\rcurrent_phase\x18\x04 \x01(\x05R\fcurrentPhase\"N\n" +
	"\x1eGetUserProjectsByStatusRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"`\n" +
	"\x1fGetUserProjectsByStatusResponse\x12=\n" +
	"\ruser_projects\x18\x01 \x03(\v2\x18.userProject.UserProjectR\fuserProjects2\xb8\x03\n" +
	"\x12UserProjectService\x12^\n" +
	"\rCreateProject\x12%.userProject.CreateUserProjectRequest\x1a&.userProject.CreateUserProjectResponse\x12e\n" +
	"\x12GetUserProjectById\x12&.userProject.GetUserProjectByIdRequest\x1a'.userProject.GetUserProjectByIdResponse\x12e\n" +
	"\x12GetAllUserProjects\x12&.userProject.GetAllUserProjectsRequest\x1a'.userProject.GetAllUserProjectsResponse\x12t\n" +
	"\x17GetUserProjectsByStatus\x12+.userProject.GetUserProjectsByStatusRequest\x1a,.userProject.GetUserProjectsByStatusResponseB\x10Z\x0egateway/pkg/pbb\x06proto3"

var (
	file_userProject_proto_rawDescOnce sync.Once
	file_userProject_proto_rawDescData []byte
)

func file_userProject_proto_rawDescGZIP() []byte {
	file_userProject_proto_rawDescOnce.Do(func() {
		file_userProject_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_userProject_proto_rawDesc), len(file_userProject_proto_rawDesc)))
	})
	return file_userProject_proto_rawDescData
}

var file_userProject_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_userProject_proto_goTypes = []any{
	(*CreateUserProjectRequest)(nil),        // 0: userProject.CreateUserProjectRequest
	(*CreateUserProjectResponse)(nil),       // 1: userProject.CreateUserProjectResponse
	(*GetUserProjectByIdRequest)(nil),       // 2: userProject.GetUserProjectByIdRequest
	(*GetUserProjectByIdResponse)(nil),      // 3: userProject.GetUserProjectByIdResponse
	(*GetAllUserProjectsRequest)(nil),       // 4: userProject.GetAllUserProjectsRequest
	(*GetAllUserProjectsResponse)(nil),      // 5: userProject.GetAllUserProjectsResponse
	(*UserProject)(nil),                     // 6: userProject.UserProject
	(*GetUserProjectsByStatusRequest)(nil),  // 7: userProject.GetUserProjectsByStatusRequest
	(*GetUserProjectsByStatusResponse)(nil), // 8: userProject.GetUserProjectsByStatusResponse
}
var file_userProject_proto_depIdxs = []int32{
	6, // 0: userProject.GetUserProjectByIdResponse.user_project:type_name -> userProject.UserProject
	6, // 1: userProject.GetAllUserProjectsResponse.user_projects:type_name -> userProject.UserProject
	6, // 2: userProject.GetUserProjectsByStatusResponse.user_projects:type_name -> userProject.UserProject
	0, // 3: userProject.UserProjectService.CreateProject:input_type -> userProject.CreateUserProjectRequest
	2, // 4: userProject.UserProjectService.GetUserProjectById:input_type -> userProject.GetUserProjectByIdRequest
	4, // 5: userProject.UserProjectService.GetAllUserProjects:input_type -> userProject.GetAllUserProjectsRequest
	7, // 6: userProject.UserProjectService.GetUserProjectsByStatus:input_type -> userProject.GetUserProjectsByStatusRequest
	1, // 7: userProject.UserProjectService.CreateProject:output_type -> userProject.CreateUserProjectResponse
	3, // 8: userProject.UserProjectService.GetUserProjectById:output_type -> userProject.GetUserProjectByIdResponse
	5, // 9: userProject.UserProjectService.GetAllUserProjects:output_type -> userProject.GetAllUserProjectsResponse
	8, // 10: userProject.UserProjectService.GetUserProjectsByStatus:output_type -> userProject.GetUserProjectsByStatusResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_userProject_proto_init() }
func file_userProject_proto_init() {
	if File_userProject_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_userProject_proto_rawDesc), len(file_userProject_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_userProject_proto_goTypes,
		DependencyIndexes: file_userProject_proto_depIdxs,
		MessageInfos:      file_userProject_proto_msgTypes,
	}.Build()
	File_userProject_proto = out.File
	file_userProject_proto_goTypes = nil
	file_userProject_proto_depIdxs = nil
}
