// /shared/proto/userProject.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: userProject.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserProjectService_CreateProject_FullMethodName           = "/userProject.UserProjectService/CreateProject"
	UserProjectService_GetUserProjectById_FullMethodName      = "/userProject.UserProjectService/GetUserProjectById"
	UserProjectService_GetAllUserProjects_FullMethodName      = "/userProject.UserProjectService/GetAllUserProjects"
	UserProjectService_GetUserProjectsByStatus_FullMethodName = "/userProject.UserProjectService/GetUserProjectsByStatus"
	UserProjectService_SetUserProjectArchived_FullMethodName  = "/userProject.UserProjectService/SetUserProjectArchived"
	UserProjectService_SubmitPhaseReview_FullMethodName       = "/userProject.UserProjectService/SubmitPhaseReview"
	UserProjectService_GetGrowth_FullMethodName               = "/userProject.UserProjectService/GetGrowth"
	UserProjectService_StartCheckpoint_FullMethodName         = "/userProject.UserProjectService/StartCheckpoint"
	UserProjectService_SubmitCheckpoint_FullMethodName        = "/userProject.UserProjectService/SubmitCheckpoint"
	UserProjectService_ShareArtifact_FullMethodName           = "/userProject.UserProjectService/ShareArtifact"
	UserProjectService_RevokeArtifact_FullMethodName          = "/userProject.UserProjectService/RevokeArtifact"
	UserProjectService_ListMyArtifacts_FullMethodName         = "/userProject.UserProjectService/ListMyArtifacts"
	UserProjectService_GetPublicArtifact_FullMethodName       = "/userProject.UserProjectService/GetPublicArtifact"
)

// UserProjectServiceClient is the client API for UserProjectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserProjectServiceClient interface {
	CreateProject(ctx context.Context, in *CreateUserProjectRequest, opts ...grpc.CallOption) (*CreateUserProjectResponse, error)
	GetUserProjectById(ctx context.Context, in *GetUserProjectByIdRequest, opts ...grpc.CallOption) (*GetUserProjectByIdResponse, error)
	GetAllUserProjects(ctx context.Context, in *GetAllUserProjectsRequest, opts ...grpc.CallOption) (*GetAllUserProjectsResponse, error)
	GetUserProjectsByStatus(ctx context.Context, in *GetUserProjectsByStatusRequest, opts ...grpc.CallOption) (*GetUserProjectsByStatusResponse, error)
	// Archives (or un-archives / "resumes") a user's project. A user may have
	// at most 1 live project (archived = false, status = in_progress) and at
	// most 1 archived project at a time — archiving the live project frees the
	// live slot to start a different one; resuming an archived project
	// requires the live slot to be free first.
	SetUserProjectArchived(ctx context.Context, in *SetUserProjectArchivedRequest, opts ...grpc.CallOption) (*SetUserProjectArchivedResponse, error)
	// Submits the user's current phase for grading, and advances it if the
	// grader judges the goal met.
	//
	// This is deliberately the ONLY path that can advance a phase. There is no
	// separate "advance" RPC: an endpoint that advances on request is an
	// endpoint any authenticated user can call to skip the work, which makes
	// every guarantee about demonstrated understanding worthless. Grading,
	// the verdict, and the advance all happen server-side inside this one call.
	//
	// The request carries only the project — the phase under review, its goal,
	// and its knowledge-check status are all derived server-side from the
	// caller's own enrollment, so none of them can be spoofed by the client.
	SubmitPhaseReview(ctx context.Context, in *SubmitPhaseReviewRequest, opts ...grpc.CallOption) (*SubmitPhaseReviewResponse, error)
	// The growth record: four stats, current era, and what the next one needs.
	//
	// Everything returned is derived from rows the user's own actions created —
	// nothing is a stored score. The four stats are deliberately returned
	// separately and never summed: a single number would let output stand in for
	// comprehension, which is the substitution this product exists to prevent.
	GetGrowth(ctx context.Context, in *GetGrowthRequest, opts ...grpc.CallOption) (*GetGrowthResponse, error)
	// Begins an explain-it-back checkpoint on a phase the user has completed,
	// returning a question grounded in the code they actually wrote.
	StartCheckpoint(ctx context.Context, in *StartCheckpointRequest, opts ...grpc.CallOption) (*StartCheckpointResponse, error)
	// Grades a checkpoint explanation. Passing is the only thing that clears fog.
	SubmitCheckpoint(ctx context.Context, in *SubmitCheckpointRequest, opts ...grpc.CallOption) (*SubmitCheckpointResponse, error)
	// Publishes a phase the user has completed AND explained back. Requiring the
	// checkpoint is the point: a shareable artifact should evidence understanding,
	// not output, or it's the credential-without-substance this product argues
	// against. It also means Show can only be earned through Understand.
	ShareArtifact(ctx context.Context, in *ShareArtifactRequest, opts ...grpc.CallOption) (*ShareArtifactResponse, error)
	// Withdraws a published artifact. Honoured immediately.
	RevokeArtifact(ctx context.Context, in *RevokeArtifactRequest, opts ...grpc.CallOption) (*RevokeArtifactResponse, error)
	// What the signed-in user has published, and which phases they could publish.
	ListMyArtifacts(ctx context.Context, in *ListMyArtifactsRequest, opts ...grpc.CallOption) (*ListMyArtifactsResponse, error)
	// Public, unauthenticated read of one published artifact.
	//
	// Everything returned is deliberately chosen: no email, no user id, nothing
	// about other projects, nothing about failed attempts. A published phase
	// reveals what the author opted into publishing and nothing adjacent to it.
	GetPublicArtifact(ctx context.Context, in *GetPublicArtifactRequest, opts ...grpc.CallOption) (*GetPublicArtifactResponse, error)
}

type userProjectServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserProjectServiceClient(cc grpc.ClientConnInterface) UserProjectServiceClient {
	return &userProjectServiceClient{cc}
}

func (c *userProjectServiceClient) CreateProject(ctx context.Context, in *CreateUserProjectRequest, opts ...grpc.CallOption) (*CreateUserProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserProjectResponse)
	err := c.cc.Invoke(ctx, UserProjectService_CreateProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userProjectServiceClient) GetUserProjectById(ctx context.Context, in *GetUserProjectByIdRequest, opts ...grpc.CallOption) (*GetUserProjectByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserProjectByIdResponse)
	err := c.cc.Invoke(ctx, UserProjectService_GetUserProjectById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userProjectServiceClient) GetAllUserProjects(ctx context.Context, in *GetAllUserProjectsRequest, opts ...grpc.CallOption) (*GetAllUserProjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllUserProjectsResponse)
	err := c.cc.Invoke(ctx, UserProjectService_GetAllUserProjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userProjectServiceClient) GetUserProjectsByStatus(ctx context.Context, in *GetUserProjectsByStatusRequest, opts ...grpc.CallOption) (*GetUserProjectsByStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserProjectsByStatusResponse)
	err := c.cc.Invoke(ctx, UserProjectService_GetUserProjectsByStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userProjectServiceClient) SetUserProjectArchived(ctx context.Context, in *SetUserProjectArchivedRequest, opts ...grpc.CallOption) (*SetUserProjectArchivedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetUserProjectArchivedResponse)
	err := c.cc.Invoke(ctx, UserProjectService_SetUserProjectArchived_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userProjectServiceClient) SubmitPhaseReview(ctx context.Context, in *SubmitPhaseReviewRequest, opts ...grpc.CallOption) (*SubmitPhaseReviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitPhaseReviewResponse)
	err := c.cc.Invoke(ctx, UserProjectService_SubmitPhaseReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userProjectServiceClient) GetGrowth(ctx context.Context, in *GetGrowthRequest, opts ...grpc.CallOption) (*GetGrowthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGrowthResponse)
	err := c.cc.Invoke(ctx, UserProjectService_GetGrowth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userProjectServiceClient) StartCheckpoint(ctx context.Context, in *StartCheckpointRequest, opts ...grpc.CallOption) (*StartCheckpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartCheckpointResponse)
	err := c.cc.Invoke(ctx, UserProjectService_StartCheckpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userProjectServiceClient) SubmitCheckpoint(ctx context.Context, in *SubmitCheckpointRequest, opts ...grpc.CallOption) (*SubmitCheckpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitCheckpointResponse)
	err := c.cc.Invoke(ctx, UserProjectService_SubmitCheckpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userProjectServiceClient) ShareArtifact(ctx context.Context, in *ShareArtifactRequest, opts ...grpc.CallOption) (*ShareArtifactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShareArtifactResponse)
	err := c.cc.Invoke(ctx, UserProjectService_ShareArtifact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userProjectServiceClient) RevokeArtifact(ctx context.Context, in *RevokeArtifactRequest, opts ...grpc.CallOption) (*RevokeArtifactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeArtifactResponse)
	err := c.cc.Invoke(ctx, UserProjectService_RevokeArtifact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userProjectServiceClient) ListMyArtifacts(ctx context.Context, in *ListMyArtifactsRequest, opts ...grpc.CallOption) (*ListMyArtifactsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMyArtifactsResponse)
	err := c.cc.Invoke(ctx, UserProjectService_ListMyArtifacts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userProjectServiceClient) GetPublicArtifact(ctx context.Context, in *GetPublicArtifactRequest, opts ...grpc.CallOption) (*GetPublicArtifactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPublicArtifactResponse)
	err := c.cc.Invoke(ctx, UserProjectService_GetPublicArtifact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserProjectServiceServer is the server API for UserProjectService service.
// All implementations must embed UnimplementedUserProjectServiceServer
// for forward compatibility.
type UserProjectServiceServer interface {
	CreateProject(context.Context, *CreateUserProjectRequest) (*CreateUserProjectResponse, error)
	GetUserProjectById(context.Context, *GetUserProjectByIdRequest) (*GetUserProjectByIdResponse, error)
	GetAllUserProjects(context.Context, *GetAllUserProjectsRequest) (*GetAllUserProjectsResponse, error)
	GetUserProjectsByStatus(context.Context, *GetUserProjectsByStatusRequest) (*GetUserProjectsByStatusResponse, error)
	// Archives (or un-archives / "resumes") a user's project. A user may have
	// at most 1 live project (archived = false, status = in_progress) and at
	// most 1 archived project at a time — archiving the live project frees the
	// live slot to start a different one; resuming an archived project
	// requires the live slot to be free first.
	SetUserProjectArchived(context.Context, *SetUserProjectArchivedRequest) (*SetUserProjectArchivedResponse, error)
	// Submits the user's current phase for grading, and advances it if the
	// grader judges the goal met.
	//
	// This is deliberately the ONLY path that can advance a phase. There is no
	// separate "advance" RPC: an endpoint that advances on request is an
	// endpoint any authenticated user can call to skip the work, which makes
	// every guarantee about demonstrated understanding worthless. Grading,
	// the verdict, and the advance all happen server-side inside this one call.
	//
	// The request carries only the project — the phase under review, its goal,
	// and its knowledge-check status are all derived server-side from the
	// caller's own enrollment, so none of them can be spoofed by the client.
	SubmitPhaseReview(context.Context, *SubmitPhaseReviewRequest) (*SubmitPhaseReviewResponse, error)
	// The growth record: four stats, current era, and what the next one needs.
	//
	// Everything returned is derived from rows the user's own actions created —
	// nothing is a stored score. The four stats are deliberately returned
	// separately and never summed: a single number would let output stand in for
	// comprehension, which is the substitution this product exists to prevent.
	GetGrowth(context.Context, *GetGrowthRequest) (*GetGrowthResponse, error)
	// Begins an explain-it-back checkpoint on a phase the user has completed,
	// returning a question grounded in the code they actually wrote.
	StartCheckpoint(context.Context, *StartCheckpointRequest) (*StartCheckpointResponse, error)
	// Grades a checkpoint explanation. Passing is the only thing that clears fog.
	SubmitCheckpoint(context.Context, *SubmitCheckpointRequest) (*SubmitCheckpointResponse, error)
	// Publishes a phase the user has completed AND explained back. Requiring the
	// checkpoint is the point: a shareable artifact should evidence understanding,
	// not output, or it's the credential-without-substance this product argues
	// against. It also means Show can only be earned through Understand.
	ShareArtifact(context.Context, *ShareArtifactRequest) (*ShareArtifactResponse, error)
	// Withdraws a published artifact. Honoured immediately.
	RevokeArtifact(context.Context, *RevokeArtifactRequest) (*RevokeArtifactResponse, error)
	// What the signed-in user has published, and which phases they could publish.
	ListMyArtifacts(context.Context, *ListMyArtifactsRequest) (*ListMyArtifactsResponse, error)
	// Public, unauthenticated read of one published artifact.
	//
	// Everything returned is deliberately chosen: no email, no user id, nothing
	// about other projects, nothing about failed attempts. A published phase
	// reveals what the author opted into publishing and nothing adjacent to it.
	GetPublicArtifact(context.Context, *GetPublicArtifactRequest) (*GetPublicArtifactResponse, error)
	mustEmbedUnimplementedUserProjectServiceServer()
}

// UnimplementedUserProjectServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserProjectServiceServer struct{}

func (UnimplementedUserProjectServiceServer) CreateProject(context.Context, *CreateUserProjectRequest) (*CreateUserProjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProject not implemented")
}
func (UnimplementedUserProjectServiceServer) GetUserProjectById(context.Context, *GetUserProjectByIdRequest) (*GetUserProjectByIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserProjectById not implemented")
}
func (UnimplementedUserProjectServiceServer) GetAllUserProjects(context.Context, *GetAllUserProjectsRequest) (*GetAllUserProjectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllUserProjects not implemented")
}
func (UnimplementedUserProjectServiceServer) GetUserProjectsByStatus(context.Context, *GetUserProjectsByStatusRequest) (*GetUserProjectsByStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserProjectsByStatus not implemented")
}
func (UnimplementedUserProjectServiceServer) SetUserProjectArchived(context.Context, *SetUserProjectArchivedRequest) (*SetUserProjectArchivedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetUserProjectArchived not implemented")
}
func (UnimplementedUserProjectServiceServer) SubmitPhaseReview(context.Context, *SubmitPhaseReviewRequest) (*SubmitPhaseReviewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitPhaseReview not implemented")
}
func (UnimplementedUserProjectServiceServer) GetGrowth(context.Context, *GetGrowthRequest) (*GetGrowthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGrowth not implemented")
}
func (UnimplementedUserProjectServiceServer) StartCheckpoint(context.Context, *StartCheckpointRequest) (*StartCheckpointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartCheckpoint not implemented")
}
func (UnimplementedUserProjectServiceServer) SubmitCheckpoint(context.Context, *SubmitCheckpointRequest) (*SubmitCheckpointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitCheckpoint not implemented")
}
func (UnimplementedUserProjectServiceServer) ShareArtifact(context.Context, *ShareArtifactRequest) (*ShareArtifactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ShareArtifact not implemented")
}
func (UnimplementedUserProjectServiceServer) RevokeArtifact(context.Context, *RevokeArtifactRequest) (*RevokeArtifactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeArtifact not implemented")
}
func (UnimplementedUserProjectServiceServer) ListMyArtifacts(context.Context, *ListMyArtifactsRequest) (*ListMyArtifactsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMyArtifacts not implemented")
}
func (UnimplementedUserProjectServiceServer) GetPublicArtifact(context.Context, *GetPublicArtifactRequest) (*GetPublicArtifactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPublicArtifact not implemented")
}
func (UnimplementedUserProjectServiceServer) mustEmbedUnimplementedUserProjectServiceServer() {}
func (UnimplementedUserProjectServiceServer) testEmbeddedByValue()                            {}

// UnsafeUserProjectServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserProjectServiceServer will
// result in compilation errors.
type UnsafeUserProjectServiceServer interface {
	mustEmbedUnimplementedUserProjectServiceServer()
}

func RegisterUserProjectServiceServer(s grpc.ServiceRegistrar, srv UserProjectServiceServer) {
	// If the following call panics, it indicates UnimplementedUserProjectServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserProjectService_ServiceDesc, srv)
}

func _UserProjectService_CreateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProjectServiceServer).CreateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserProjectService_CreateProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProjectServiceServer).CreateProject(ctx, req.(*CreateUserProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserProjectService_GetUserProjectById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserProjectByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProjectServiceServer).GetUserProjectById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserProjectService_GetUserProjectById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProjectServiceServer).GetUserProjectById(ctx, req.(*GetUserProjectByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserProjectService_GetAllUserProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllUserProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProjectServiceServer).GetAllUserProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserProjectService_GetAllUserProjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProjectServiceServer).GetAllUserProjects(ctx, req.(*GetAllUserProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserProjectService_GetUserProjectsByStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserProjectsByStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProjectServiceServer).GetUserProjectsByStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserProjectService_GetUserProjectsByStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProjectServiceServer).GetUserProjectsByStatus(ctx, req.(*GetUserProjectsByStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserProjectService_SetUserProjectArchived_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserProjectArchivedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProjectServiceServer).SetUserProjectArchived(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserProjectService_SetUserProjectArchived_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProjectServiceServer).SetUserProjectArchived(ctx, req.(*SetUserProjectArchivedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserProjectService_SubmitPhaseReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitPhaseReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProjectServiceServer).SubmitPhaseReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserProjectService_SubmitPhaseReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProjectServiceServer).SubmitPhaseReview(ctx, req.(*SubmitPhaseReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserProjectService_GetGrowth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGrowthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProjectServiceServer).GetGrowth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserProjectService_GetGrowth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProjectServiceServer).GetGrowth(ctx, req.(*GetGrowthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserProjectService_StartCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProjectServiceServer).StartCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserProjectService_StartCheckpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProjectServiceServer).StartCheckpoint(ctx, req.(*StartCheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserProjectService_SubmitCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProjectServiceServer).SubmitCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserProjectService_SubmitCheckpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProjectServiceServer).SubmitCheckpoint(ctx, req.(*SubmitCheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserProjectService_ShareArtifact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareArtifactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProjectServiceServer).ShareArtifact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserProjectService_ShareArtifact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProjectServiceServer).ShareArtifact(ctx, req.(*ShareArtifactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserProjectService_RevokeArtifact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeArtifactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProjectServiceServer).RevokeArtifact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserProjectService_RevokeArtifact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProjectServiceServer).RevokeArtifact(ctx, req.(*RevokeArtifactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserProjectService_ListMyArtifacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyArtifactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProjectServiceServer).ListMyArtifacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserProjectService_ListMyArtifacts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProjectServiceServer).ListMyArtifacts(ctx, req.(*ListMyArtifactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserProjectService_GetPublicArtifact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublicArtifactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProjectServiceServer).GetPublicArtifact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserProjectService_GetPublicArtifact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProjectServiceServer).GetPublicArtifact(ctx, req.(*GetPublicArtifactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserProjectService_ServiceDesc is the grpc.ServiceDesc for UserProjectService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserProjectService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "userProject.UserProjectService",
	HandlerType: (*UserProjectServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProject",
			Handler:    _UserProjectService_CreateProject_Handler,
		},
		{
			MethodName: "GetUserProjectById",
			Handler:    _UserProjectService_GetUserProjectById_Handler,
		},
		{
			MethodName: "GetAllUserProjects",
			Handler:    _UserProjectService_GetAllUserProjects_Handler,
		},
		{
			MethodName: "GetUserProjectsByStatus",
			Handler:    _UserProjectService_GetUserProjectsByStatus_Handler,
		},
		{
			MethodName: "SetUserProjectArchived",
			Handler:    _UserProjectService_SetUserProjectArchived_Handler,
		},
		{
			MethodName: "SubmitPhaseReview",
			Handler:    _UserProjectService_SubmitPhaseReview_Handler,
		},
		{
			MethodName: "GetGrowth",
			Handler:    _UserProjectService_GetGrowth_Handler,
		},
		{
			MethodName: "StartCheckpoint",
			Handler:    _UserProjectService_StartCheckpoint_Handler,
		},
		{
			MethodName: "SubmitCheckpoint",
			Handler:    _UserProjectService_SubmitCheckpoint_Handler,
		},
		{
			MethodName: "ShareArtifact",
			Handler:    _UserProjectService_ShareArtifact_Handler,
		},
		{
			MethodName: "RevokeArtifact",
			Handler:    _UserProjectService_RevokeArtifact_Handler,
		},
		{
			MethodName: "ListMyArtifacts",
			Handler:    _UserProjectService_ListMyArtifacts_Handler,
		},
		{
			MethodName: "GetPublicArtifact",
			Handler:    _UserProjectService_GetPublicArtifact_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "userProject.proto",
}
