// /shared/proto/userProject.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: userProject.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserProjectService_CreateProject_FullMethodName      = "/userProject.UserProjectService/CreateProject"
	UserProjectService_GetUserProjectById_FullMethodName = "/userProject.UserProjectService/GetUserProjectById"
	UserProjectService_GetAllUserProjects_FullMethodName = "/userProject.UserProjectService/GetAllUserProjects"
)

// UserProjectServiceClient is the client API for UserProjectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserProjectServiceClient interface {
	CreateProject(ctx context.Context, in *CreateUserProjectRequest, opts ...grpc.CallOption) (*CreateUserProjectResponse, error)
	GetUserProjectById(ctx context.Context, in *GetUserProjectByIdRequest, opts ...grpc.CallOption) (*GetUserProjectByIdResponse, error)
	GetAllUserProjects(ctx context.Context, in *GetAllUserProjectsRequest, opts ...grpc.CallOption) (*GetAllUserProjectsResponse, error)
}

type userProjectServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserProjectServiceClient(cc grpc.ClientConnInterface) UserProjectServiceClient {
	return &userProjectServiceClient{cc}
}

func (c *userProjectServiceClient) CreateProject(ctx context.Context, in *CreateUserProjectRequest, opts ...grpc.CallOption) (*CreateUserProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserProjectResponse)
	err := c.cc.Invoke(ctx, UserProjectService_CreateProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userProjectServiceClient) GetUserProjectById(ctx context.Context, in *GetUserProjectByIdRequest, opts ...grpc.CallOption) (*GetUserProjectByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserProjectByIdResponse)
	err := c.cc.Invoke(ctx, UserProjectService_GetUserProjectById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userProjectServiceClient) GetAllUserProjects(ctx context.Context, in *GetAllUserProjectsRequest, opts ...grpc.CallOption) (*GetAllUserProjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllUserProjectsResponse)
	err := c.cc.Invoke(ctx, UserProjectService_GetAllUserProjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserProjectServiceServer is the server API for UserProjectService service.
// All implementations must embed UnimplementedUserProjectServiceServer
// for forward compatibility.
type UserProjectServiceServer interface {
	CreateProject(context.Context, *CreateUserProjectRequest) (*CreateUserProjectResponse, error)
	GetUserProjectById(context.Context, *GetUserProjectByIdRequest) (*GetUserProjectByIdResponse, error)
	GetAllUserProjects(context.Context, *GetAllUserProjectsRequest) (*GetAllUserProjectsResponse, error)
	mustEmbedUnimplementedUserProjectServiceServer()
}

// UnimplementedUserProjectServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserProjectServiceServer struct{}

func (UnimplementedUserProjectServiceServer) CreateProject(context.Context, *CreateUserProjectRequest) (*CreateUserProjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProject not implemented")
}
func (UnimplementedUserProjectServiceServer) GetUserProjectById(context.Context, *GetUserProjectByIdRequest) (*GetUserProjectByIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserProjectById not implemented")
}
func (UnimplementedUserProjectServiceServer) GetAllUserProjects(context.Context, *GetAllUserProjectsRequest) (*GetAllUserProjectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllUserProjects not implemented")
}
func (UnimplementedUserProjectServiceServer) mustEmbedUnimplementedUserProjectServiceServer() {}
func (UnimplementedUserProjectServiceServer) testEmbeddedByValue()                            {}

// UnsafeUserProjectServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserProjectServiceServer will
// result in compilation errors.
type UnsafeUserProjectServiceServer interface {
	mustEmbedUnimplementedUserProjectServiceServer()
}

func RegisterUserProjectServiceServer(s grpc.ServiceRegistrar, srv UserProjectServiceServer) {
	// If the following call panics, it indicates UnimplementedUserProjectServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserProjectService_ServiceDesc, srv)
}

func _UserProjectService_CreateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProjectServiceServer).CreateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserProjectService_CreateProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProjectServiceServer).CreateProject(ctx, req.(*CreateUserProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserProjectService_GetUserProjectById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserProjectByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProjectServiceServer).GetUserProjectById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserProjectService_GetUserProjectById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProjectServiceServer).GetUserProjectById(ctx, req.(*GetUserProjectByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserProjectService_GetAllUserProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllUserProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProjectServiceServer).GetAllUserProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserProjectService_GetAllUserProjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProjectServiceServer).GetAllUserProjects(ctx, req.(*GetAllUserProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserProjectService_ServiceDesc is the grpc.ServiceDesc for UserProjectService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserProjectService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "userProject.UserProjectService",
	HandlerType: (*UserProjectServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProject",
			Handler:    _UserProjectService_CreateProject_Handler,
		},
		{
			MethodName: "GetUserProjectById",
			Handler:    _UserProjectService_GetUserProjectById_Handler,
		},
		{
			MethodName: "GetAllUserProjects",
			Handler:    _UserProjectService_GetAllUserProjects_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "userProject.proto",
}
