// /shared/proto/userProject.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: userProject.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShareArtifactRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Email       string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	ProjectId   string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	PhaseNumber int32                  `protobuf:"varint,3,opt,name=phase_number,json=phaseNumber,proto3" json:"phase_number,omitempty"`
	// Publish the frozen snapshot of their code alongside the explanation.
	IncludeCode   bool `protobuf:"varint,4,opt,name=include_code,json=includeCode,proto3" json:"include_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareArtifactRequest) Reset() {
	*x = ShareArtifactRequest{}
	mi := &file_userProject_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareArtifactRequest) ProtoMessage() {}

func (x *ShareArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userProject_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareArtifactRequest.ProtoReflect.Descriptor instead.
func (*ShareArtifactRequest) Descriptor() ([]byte, []int) {
	return file_userProject_proto_rawDescGZIP(), []int{0}
}

func (x *ShareArtifactRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ShareArtifactRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ShareArtifactRequest) GetPhaseNumber() int32 {
	if x != nil {
		return x.PhaseNumber
	}
	return 0
}

func (x *ShareArtifactRequest) GetIncludeCode() bool {
	if x != nil {
		return x.IncludeCode
	}
	return false
}

type ShareArtifactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareArtifactResponse) Reset() {
	*x = ShareArtifactResponse{}
	mi := &file_userProject_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareArtifactResponse) ProtoMessage() {}

func (x *ShareArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userProject_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareArtifactResponse.ProtoReflect.Descriptor instead.
func (*ShareArtifactResponse) Descriptor() ([]byte, []int) {
	return file_userProject_proto_rawDescGZIP(), []int{1}
}

func (x *ShareArtifactResponse) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type RevokeArtifactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeArtifactRequest) Reset() {
	*x = RevokeArtifactRequest{}
	mi := &file_userProject_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeArtifactRequest) ProtoMessage() {}

func (x *RevokeArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userProject_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeArtifactRequest.ProtoReflect.Descriptor instead.
func (*RevokeArtifactRequest) Descriptor() ([]byte, []int) {
	return file_userProject_proto_rawDescGZIP(), []int{2}
}

func (x *RevokeArtifactRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RevokeArtifactRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type RevokeArtifactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revoked       bool                   `protobuf:"varint,1,opt,name=revoked,proto3" json:"revoked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeArtifactResponse) Reset() {
	*x = RevokeArtifactResponse{}
	mi := &file_userProject_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeArtifactResponse) ProtoMessage() {}

func (x *RevokeArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userProject_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeArtifactResponse.ProtoReflect.Descriptor instead.
func (*RevokeArtifactResponse) Descriptor() ([]byte, []int) {
	return file_userProject_proto_rawDescGZIP(), []int{3}
}

func (x *RevokeArtifactResponse) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

type ListMyArtifactsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyArtifactsRequest) Reset() {
	*x = ListMyArtifactsRequest{}
	mi := &file_userProject_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyArtifactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyArtifactsRequest) ProtoMessage() {}

func (x *ListMyArtifactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userProject_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyArtifactsRequest.ProtoReflect.Descriptor instead.
func (*ListMyArtifactsRequest) Descriptor() ([]byte, []int) {
	return file_userProject_proto_rawDescGZIP(), []int{4}
}

func (x *ListMyArtifactsRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type MyArtifactProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ProjectName   string                 `protobuf:"bytes,3,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	PhaseNumber   int32                  `protobuf:"varint,4,opt,name=phase_number,json=phaseNumber,proto3" json:"phase_number,omitempty"`
	PhaseTitle    string                 `protobuf:"bytes,5,opt,name=phase_title,json=phaseTitle,proto3" json:"phase_title,omitempty"`
	IncludeCode   bool                   `protobuf:"varint,6,opt,name=include_code,json=includeCode,proto3" json:"include_code,omitempty"`
	ViewCount     int32                  `protobuf:"varint,7,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyArtifactProto) Reset() {
	*x = MyArtifactProto{}
	mi := &file_userProject_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyArtifactProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyArtifactProto) ProtoMessage() {}

func (x *MyArtifactProto) ProtoReflect() protoreflect.Message {
	mi := &file_userProject_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyArtifactProto.ProtoReflect.Descriptor instead.
func (*MyArtifactProto) Descriptor() ([]byte, []int) {
	return file_userProject_proto_rawDescGZIP(), []int{5}
}

func (x *MyArtifactProto) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *MyArtifactProto) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *MyArtifactProto) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *MyArtifactProto) GetPhaseNumber() int32 {
	if x != nil {
		return x.PhaseNumber
	}
	return 0
}

func (x *MyArtifactProto) GetPhaseTitle() string {
	if x != nil {
		return x.PhaseTitle
	}
	return ""
}

func (x *MyArtifactProto) GetIncludeCode() bool {
	if x != nil {
		return x.IncludeCode
	}
	return false
}

func (x *MyArtifactProto) GetViewCount() int32 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

// A phase that could be published but hasn't been — completed and explained.
type ShareablePhaseProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ProjectName   string                 `protobuf:"bytes,2,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	PhaseNumber   int32                  `protobuf:"varint,3,opt,name=phase_number,json=phaseNumber,proto3" json:"phase_number,omitempty"`
	PhaseTitle    string                 `protobuf:"bytes,4,opt,name=phase_title,json=phaseTitle,proto3" json:"phase_title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareablePhaseProto) Reset() {
	*x = ShareablePhaseProto{}
	mi := &file_userProject_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareablePhaseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareablePhaseProto) ProtoMessage() {}

func (x *ShareablePhaseProto) ProtoReflect() protoreflect.Message {
	mi := &file_userProject_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareablePhaseProto.ProtoReflect.Descriptor instead.
func (*ShareablePhaseProto) Descriptor() ([]byte, []int) {
	return file_userProject_proto_rawDescGZIP(), []int{6}
}

func (x *ShareablePhaseProto) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ShareablePhaseProto) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *ShareablePhaseProto) GetPhaseNumber() int32 {
	if x != nil {
		return x.PhaseNumber
	}
	return 0
}

func (x *ShareablePhaseProto) GetPhaseTitle() string {
	if x != nil {
		return x.PhaseTitle
	}
	return ""
}

type ListMyArtifactsResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Shared    []*MyArtifactProto     `protobuf:"bytes,1,rep,name=shared,proto3" json:"shared,omitempty"`
	Shareable []*ShareablePhaseProto `protobuf:"bytes,2,rep,name=shareable,proto3" json:"shareable,omitempty"`
	// Public profiles unlock at the Builder era. Individual phases can be shared
	// before that; the aggregated profile is what's milestone-gated.
	ProfileUnlocked     bool   `protobuf:"varint,3,opt,name=profile_unlocked,json=profileUnlocked,proto3" json:"profile_unlocked,omitempty"`
	ProfileLockedReason string `protobuf:"bytes,4,opt,name=profile_locked_reason,json=profileLockedReason,proto3" json:"profile_locked_reason,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ListMyArtifactsResponse) Reset() {
	*x = ListMyArtifactsResponse{}
	mi := &file_userProject_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyArtifactsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyArtifactsResponse) ProtoMessage() {}

func (x *ListMyArtifactsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userProject_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyArtifactsResponse.ProtoReflect.Descriptor instead.
func (*ListMyArtifactsResponse) Descriptor() ([]byte, []int) {
	return file_userProject_proto_rawDescGZIP(), []int{7}
}

func (x *ListMyArtifactsResponse) GetShared() []*MyArtifactProto {
	if x != nil {
		return x.Shared
	}
	return nil
}

func (x *ListMyArtifactsResponse) GetShareable() []*ShareablePhaseProto {
	if x != nil {
		return x.Shareable
	}
	return nil
}

func (x *ListMyArtifactsResponse) GetProfileUnlocked() bool {
	if x != nil {
		return x.ProfileUnlocked
	}
	return false
}

func (x *ListMyArtifactsResponse) GetProfileLockedReason() string {
	if x != nil {
		return x.ProfileLockedReason
	}
	return ""
}

type GetPublicArtifactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicArtifactRequest) Reset() {
	*x = GetPublicArtifactRequest{}
	mi := &file_userProject_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicArtifactRequest) ProtoMessage() {}

func (x *GetPublicArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userProject_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicArtifactRequest.ProtoReflect.Descriptor instead.
func (*GetPublicArtifactRequest) Descriptor() ([]byte, []int) {
	return file_userProject_proto_rawDescGZIP(), []int{8}
}

func (x *GetPublicArtifactRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type PublicCriterionProto struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Text  string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Kind  string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// Where the grader found the evidence. Included because "passed" alone is a
	// badge; a badge plus the line it was verified against is proof.
	EvidencePath  string `protobuf:"bytes,3,opt,name=evidence_path,json=evidencePath,proto3" json:"evidence_path,omitempty"`
	EvidenceLines string `protobuf:"bytes,4,opt,name=evidence_lines,json=evidenceLines,proto3" json:"evidence_lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicCriterionProto) Reset() {
	*x = PublicCriterionProto{}
	mi := &file_userProject_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicCriterionProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicCriterionProto) ProtoMessage() {}

func (x *PublicCriterionProto) ProtoReflect() protoreflect.Message {
	mi := &file_userProject_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicCriterionProto.ProtoReflect.Descriptor instead.
func (*PublicCriterionProto) Descriptor() ([]byte, []int) {
	return file_userProject_proto_rawDescGZIP(), []int{9}
}

func (x *PublicCriterionProto) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *PublicCriterionProto) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *PublicCriterionProto) GetEvidencePath() string {
	if x != nil {
		return x.EvidencePath
	}
	return ""
}

func (x *PublicCriterionProto) GetEvidenceLines() string {
	if x != nil {
		return x.EvidenceLines
	}
	return ""
}

type PublicFileProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicFileProto) Reset() {
	*x = PublicFileProto{}
	mi := &file_userProject_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicFileProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicFileProto) ProtoMessage() {}

func (x *PublicFileProto) ProtoReflect() protoreflect.Message {
	mi := &file_userProject_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicFileProto.ProtoReflect.Descriptor instead.
func (*PublicFileProto) Descriptor() ([]byte, []int) {
	return file_userProject_proto_rawDescGZIP(), []int{10}
}

func (x *PublicFileProto) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PublicFileProto) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type GetPublicArtifactResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Found bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	// True when the link was valid but the author has since withdrawn it — so the
	// page can say so rather than looking broken.
	Revoked bool `protobuf:"varint,2,opt,name=revoked,proto3" json:"revoked,omitempty"`
	// Display name only. Never the email.
	AuthorName  string                  `protobuf:"bytes,3,opt,name=author_name,json=authorName,proto3" json:"author_name,omitempty"`
	ProjectName string                  `protobuf:"bytes,4,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	PhaseNumber int32                   `protobuf:"varint,5,opt,name=phase_number,json=phaseNumber,proto3" json:"phase_number,omitempty"`
	PhaseTitle  string                  `protobuf:"bytes,6,opt,name=phase_title,json=phaseTitle,proto3" json:"phase_title,omitempty"`
	CreatedAt   string                  `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Criteria    []*PublicCriterionProto `protobuf:"bytes,8,rep,name=criteria,proto3" json:"criteria,omitempty"`
	// The explain-it-back exchange. This is the substance of the artifact: the
	// criteria show the code works, this shows they understood it.
	ExplanationQuestion string             `protobuf:"bytes,9,opt,name=explanation_question,json=explanationQuestion,proto3" json:"explanation_question,omitempty"`
	ExplanationAnswer   string             `protobuf:"bytes,10,opt,name=explanation_answer,json=explanationAnswer,proto3" json:"explanation_answer,omitempty"`
	Files               []*PublicFileProto `protobuf:"bytes,11,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetPublicArtifactResponse) Reset() {
	*x = GetPublicArtifactResponse{}
	mi := &file_userProject_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicArtifactResponse) ProtoMessage() {}

func (x *GetPublicArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userProject_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicArtifactResponse.ProtoReflect.Descriptor instead.
func (*GetPublicArtifactResponse) Descriptor() ([]byte, []int) {
	return file_userProject_proto_rawDescGZIP(), []int{11}
}

func (x *GetPublicArtifactResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetPublicArtifactResponse) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

func (x *GetPublicArtifactResponse) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *GetPublicArtifactResponse) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *GetPublicArtifactResponse) GetPhaseNumber() int32 {
	if x != nil {
		return x.PhaseNumber
	}
	return 0
}

func (x *GetPublicArtifactResponse) GetPhaseTitle() string {
	if x != nil {
		return x.PhaseTitle
	}
	return ""
}

func (x *GetPublicArtifactResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetPublicArtifactResponse) GetCriteria() []*PublicCriterionProto {
	if x != nil {
		return x.Criteria
	}
	return nil
}

func (x *GetPublicArtifactResponse) GetExplanationQuestion() string {
	if x != nil {
		return x.ExplanationQuestion
	}
	return ""
}

func (x *GetPublicArtifactResponse) GetExplanationAnswer() string {
	if x != nil {
		return x.ExplanationAnswer
	}
	return ""
}

func (x *GetPublicArtifactResponse) GetFiles() []*PublicFileProto {
	if x != nil {
		return x.Files
	}
	return nil
}

type GetGrowthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGrowthRequest) Reset() {
	*x = GetGrowthRequest{}
	mi := &file_userProject_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGrowthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGrowthRequest) ProtoMessage() {}

func (x *GetGrowthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userProject_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGrowthRequest.ProtoReflect.Descriptor instead.
func (*GetGrowthRequest) Descriptor() ([]byte, []int) {
	return file_userProject_proto_rawDescGZIP(), []int{12}
}

func (x *GetGrowthRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type EraRequirementProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"` // phrased for a human; shown verbatim
	Met           bool                   `protobuf:"varint,2,opt,name=met,proto3" json:"met,omitempty"`
	Have          int32                  `protobuf:"varint,3,opt,name=have,proto3" json:"have,omitempty"`
	Need          int32                  `protobuf:"varint,4,opt,name=need,proto3" json:"need,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EraRequirementProto) Reset() {
	*x = EraRequirementProto{}
	mi := &file_userProject_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EraRequirementProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EraRequirementProto) ProtoMessage() {}

func (x *EraRequirementProto) ProtoReflect() protoreflect.Message {
	mi := &file_userProject_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EraRequirementProto.ProtoReflect.Descriptor instead.
func (*EraRequirementProto) Descriptor() ([]byte, []int) {
	return file_userProject_proto_rawDescGZIP(), []int{13}
}

func (x *EraRequirementProto) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *EraRequirementProto) GetMet() bool {
	if x != nil {
		return x.Met
	}
	return false
}

func (x *EraRequirementProto) GetHave() int32 {
	if x != nil {
		return x.Have
	}
	return 0
}

func (x *EraRequirementProto) GetNeed() int32 {
	if x != nil {
		return x.Need
	}
	return 0
}

type UnexplainedPhaseProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ProjectName   string                 `protobuf:"bytes,2,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	PhaseNumber   int32                  `protobuf:"varint,3,opt,name=phase_number,json=phaseNumber,proto3" json:"phase_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnexplainedPhaseProto) Reset() {
	*x = UnexplainedPhaseProto{}
	mi := &file_userProject_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnexplainedPhaseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnexplainedPhaseProto) ProtoMessage() {}

func (x *UnexplainedPhaseProto) ProtoReflect() protoreflect.Message {
	mi := &file_userProject_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnexplainedPhaseProto.ProtoReflect.Descriptor instead.
func (*UnexplainedPhaseProto) Descriptor() ([]byte, []int) {
	return file_userProject_proto_rawDescGZIP(), []int{14}
}

func (x *UnexplainedPhaseProto) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *UnexplainedPhaseProto) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *UnexplainedPhaseProto) GetPhaseNumber() int32 {
	if x != nil {
		return x.PhaseNumber
	}
	return 0
}

type GetGrowthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Never blended. Four numbers, always four.
	Build            int32                  `protobuf:"varint,1,opt,name=build,proto3" json:"build,omitempty"`
	Understand       int32                  `protobuf:"varint,2,opt,name=understand,proto3" json:"understand,omitempty"`
	Explore          int32                  `protobuf:"varint,3,opt,name=explore,proto3" json:"explore,omitempty"`
	Show             int32                  `protobuf:"varint,4,opt,name=show,proto3" json:"show,omitempty"`
	EraName          string                 `protobuf:"bytes,5,opt,name=era_name,json=eraName,proto3" json:"era_name,omitempty"`
	EraBlurb         string                 `protobuf:"bytes,6,opt,name=era_blurb,json=eraBlurb,proto3" json:"era_blurb,omitempty"`
	EraIndex         int32                  `protobuf:"varint,7,opt,name=era_index,json=eraIndex,proto3" json:"era_index,omitempty"`
	NextEraName      string                 `protobuf:"bytes,8,opt,name=next_era_name,json=nextEraName,proto3" json:"next_era_name,omitempty"`
	NextRequirements []*EraRequirementProto `protobuf:"bytes,9,rep,name=next_requirements,json=nextRequirements,proto3" json:"next_requirements,omitempty"`
	// Fog: work shipped but never explained back. A property of the record, not
	// a judgement about the person.
	FogCount      int32                    `protobuf:"varint,10,opt,name=fog_count,json=fogCount,proto3" json:"fog_count,omitempty"`
	Unexplained   []*UnexplainedPhaseProto `protobuf:"bytes,11,rep,name=unexplained,proto3" json:"unexplained,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGrowthResponse) Reset() {
	*x = GetGrowthResponse{}
	mi := &file_userProject_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGrowthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGrowthResponse) ProtoMessage() {}

func (x *GetGrowthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userProject_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGrowthResponse.ProtoReflect.Descriptor instead.
func (*GetGrowthResponse) Descriptor() ([]byte, []int) {
	return file_userProject_proto_rawDescGZIP(), []int{15}
}

func (x *GetGrowthResponse) GetBuild() int32 {
	if x != nil {
		return x.Build
	}
	return 0
}

func (x *GetGrowthResponse) GetUnderstand() int32 {
	if x != nil {
		return x.Understand
	}
	return 0
}

func (x *GetGrowthResponse) GetExplore() int32 {
	if x != nil {
		return x.Explore
	}
	return 0
}

func (x *GetGrowthResponse) GetShow() int32 {
	if x != nil {
		return x.Show
	}
	return 0
}

func (x *GetGrowthResponse) GetEraName() string {
	if x != nil {
		return x.EraName
	}
	return ""
}

func (x *GetGrowthResponse) GetEraBlurb() string {
	if x != nil {
		return x.EraBlurb
	}
	return ""
}

func (x *GetGrowthResponse) GetEraIndex() int32 {
	if x != nil {
		return x.EraIndex
	}
	return 0
}

func (x *GetGrowthResponse) GetNextEraName() string {
	if x != nil {
		return x.NextEraName
	}
	return ""
}

func (x *GetGrowthResponse) GetNextRequirements() []*EraRequirementProto {
	if x != nil {
		return x.NextRequirements
	}
	return nil
}

func (x *GetGrowthResponse) GetFogCount() int32 {
	if x != nil {
		return x.FogCount
	}
	return 0
}

func (x *GetGrowthResponse) GetUnexplained() []*UnexplainedPhaseProto {
	if x != nil {
		return x.Unexplained
	}
	return nil
}

type StartCheckpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	PhaseNumber   int32                  `protobuf:"varint,3,opt,name=phase_number,json=phaseNumber,proto3" json:"phase_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartCheckpointRequest) Reset() {
	*x = StartCheckpointRequest{}
	mi := &file_userProject_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartCheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCheckpointRequest) ProtoMessage() {}

func (x *StartCheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userProject_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCheckpointRequest.ProtoReflect.Descriptor instead.
func (*StartCheckpointRequest) Descriptor() ([]byte, []int) {
	return file_userProject_proto_rawDescGZIP(), []int{16}
}

func (x *StartCheckpointRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *StartCheckpointRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *StartCheckpointRequest) GetPhaseNumber() int32 {
	if x != nil {
		return x.PhaseNumber
	}
	return 0
}

type StartCheckpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckpointId  string                 `protobuf:"bytes,1,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	Question      string                 `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartCheckpointResponse) Reset() {
	*x = StartCheckpointResponse{}
	mi := &file_userProject_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartCheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCheckpointResponse) ProtoMessage() {}

func (x *StartCheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userProject_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCheckpointResponse.ProtoReflect.Descriptor instead.
func (*StartCheckpointResponse) Descriptor() ([]byte, []int) {
	return file_userProject_proto_rawDescGZIP(), []int{17}
}

func (x *StartCheckpointResponse) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

func (x *StartCheckpointResponse) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

type SubmitCheckpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	CheckpointId  string                 `protobuf:"bytes,2,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	Answer        string                 `protobuf:"bytes,3,opt,name=answer,proto3" json:"answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitCheckpointRequest) Reset() {
	*x = SubmitCheckpointRequest{}
	mi := &file_userProject_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitCheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitCheckpointRequest) ProtoMessage() {}

func (x *SubmitCheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userProject_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitCheckpointRequest.ProtoReflect.Descriptor instead.
func (*SubmitCheckpointRequest) Descriptor() ([]byte, []int) {
	return file_userProject_proto_rawDescGZIP(), []int{18}
}

func (x *SubmitCheckpointRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SubmitCheckpointRequest) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

func (x *SubmitCheckpointRequest) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

type SubmitCheckpointResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Passed          bool                   `protobuf:"varint,1,opt,name=passed,proto3" json:"passed,omitempty"`
	Feedback        string                 `protobuf:"bytes,2,opt,name=feedback,proto3" json:"feedback,omitempty"`
	MissingConcepts []string               `protobuf:"bytes,3,rep,name=missing_concepts,json=missingConcepts,proto3" json:"missing_concepts,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SubmitCheckpointResponse) Reset() {
	*x = SubmitCheckpointResponse{}
	mi := &file_userProject_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitCheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitCheckpointResponse) ProtoMessage() {}

func (x *SubmitCheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userProject_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitCheckpointResponse.ProtoReflect.Descriptor instead.
func (*SubmitCheckpointResponse) Descriptor() ([]byte, []int) {
	return file_userProject_proto_rawDescGZIP(), []int{19}
}

func (x *SubmitCheckpointResponse) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *SubmitCheckpointResponse) GetFeedback() string {
	if x != nil {
		return x.Feedback
	}
	return ""
}

func (x *SubmitCheckpointResponse) GetMissingConcepts() []string {
	if x != nil {
		return x.MissingConcepts
	}
	return nil
}

type CreateUserProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CurrentPhase  int32                  `protobuf:"varint,4,opt,name=current_phase,json=currentPhase,proto3" json:"current_phase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserProjectRequest) Reset() {
	*x = CreateUserProjectRequest{}
	mi := &file_userProject_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserProjectRequest) ProtoMessage() {}

func (x *CreateUserProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userProject_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserProjectRequest.ProtoReflect.Descriptor instead.
func (*CreateUserProjectRequest) Descriptor() ([]byte, []int) {
	return file_userProject_proto_rawDescGZIP(), []int{20}
}

func (x *CreateUserProjectRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateUserProjectRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserProjectRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateUserProjectRequest) GetCurrentPhase() int32 {
	if x != nil {
		return x.CurrentPhase
	}
	return 0
}

type CreateUserProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserProjectResponse) Reset() {
	*x = CreateUserProjectResponse{}
	mi := &file_userProject_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserProjectResponse) ProtoMessage() {}

func (x *CreateUserProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userProject_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserProjectResponse.ProtoReflect.Descriptor instead.
func (*CreateUserProjectResponse) Descriptor() ([]byte, []int) {
	return file_userProject_proto_rawDescGZIP(), []int{21}
}

func (x *CreateUserProjectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetUserProjectByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProjectByIdRequest) Reset() {
	*x = GetUserProjectByIdRequest{}
	mi := &file_userProject_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProjectByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProjectByIdRequest) ProtoMessage() {}

func (x *GetUserProjectByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userProject_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProjectByIdRequest.ProtoReflect.Descriptor instead.
func (*GetUserProjectByIdRequest) Descriptor() ([]byte, []int) {
	return file_userProject_proto_rawDescGZIP(), []int{22}
}

func (x *GetUserProjectByIdRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type GetUserProjectByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserProject   *UserProject           `protobuf:"bytes,1,opt,name=user_project,json=userProject,proto3" json:"user_project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProjectByIdResponse) Reset() {
	*x = GetUserProjectByIdResponse{}
	mi := &file_userProject_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProjectByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProjectByIdResponse) ProtoMessage() {}

func (x *GetUserProjectByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userProject_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProjectByIdResponse.ProtoReflect.Descriptor instead.
func (*GetUserProjectByIdResponse) Descriptor() ([]byte, []int) {
	return file_userProject_proto_rawDescGZIP(), []int{23}
}

func (x *GetUserProjectByIdResponse) GetUserProject() *UserProject {
	if x != nil {
		return x.UserProject
	}
	return nil
}

type GetAllUserProjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllUserProjectsRequest) Reset() {
	*x = GetAllUserProjectsRequest{}
	mi := &file_userProject_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllUserProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUserProjectsRequest) ProtoMessage() {}

func (x *GetAllUserProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userProject_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUserProjectsRequest.ProtoReflect.Descriptor instead.
func (*GetAllUserProjectsRequest) Descriptor() ([]byte, []int) {
	return file_userProject_proto_rawDescGZIP(), []int{24}
}

func (x *GetAllUserProjectsRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetAllUserProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserProjects  []*UserProject         `protobuf:"bytes,1,rep,name=user_projects,json=userProjects,proto3" json:"user_projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllUserProjectsResponse) Reset() {
	*x = GetAllUserProjectsResponse{}
	mi := &file_userProject_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllUserProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUserProjectsResponse) ProtoMessage() {}

func (x *GetAllUserProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userProject_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUserProjectsResponse.ProtoReflect.Descriptor instead.
func (*GetAllUserProjectsResponse) Descriptor() ([]byte, []int) {
	return file_userProject_proto_rawDescGZIP(), []int{25}
}

func (x *GetAllUserProjectsResponse) GetUserProjects() []*UserProject {
	if x != nil {
		return x.UserProjects
	}
	return nil
}

type UserProject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CurrentPhase  int32                  `protobuf:"varint,4,opt,name=current_phase,json=currentPhase,proto3" json:"current_phase,omitempty"`
	Archived      bool                   `protobuf:"varint,5,opt,name=archived,proto3" json:"archived,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProject) Reset() {
	*x = UserProject{}
	mi := &file_userProject_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProject) ProtoMessage() {}

func (x *UserProject) ProtoReflect() protoreflect.Message {
	mi := &file_userProject_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProject.ProtoReflect.Descriptor instead.
func (*UserProject) Descriptor() ([]byte, []int) {
	return file_userProject_proto_rawDescGZIP(), []int{26}
}

func (x *UserProject) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *UserProject) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserProject) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UserProject) GetCurrentPhase() int32 {
	if x != nil {
		return x.CurrentPhase
	}
	return 0
}

func (x *UserProject) GetArchived() bool {
	if x != nil {
		return x.Archived
	}
	return false
}

type GetUserProjectsByStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProjectsByStatusRequest) Reset() {
	*x = GetUserProjectsByStatusRequest{}
	mi := &file_userProject_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProjectsByStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProjectsByStatusRequest) ProtoMessage() {}

func (x *GetUserProjectsByStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userProject_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProjectsByStatusRequest.ProtoReflect.Descriptor instead.
func (*GetUserProjectsByStatusRequest) Descriptor() ([]byte, []int) {
	return file_userProject_proto_rawDescGZIP(), []int{27}
}

func (x *GetUserProjectsByStatusRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetUserProjectsByStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetUserProjectsByStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserProjects  []*UserProject         `protobuf:"bytes,1,rep,name=user_projects,json=userProjects,proto3" json:"user_projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProjectsByStatusResponse) Reset() {
	*x = GetUserProjectsByStatusResponse{}
	mi := &file_userProject_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProjectsByStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProjectsByStatusResponse) ProtoMessage() {}

func (x *GetUserProjectsByStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userProject_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProjectsByStatusResponse.ProtoReflect.Descriptor instead.
func (*GetUserProjectsByStatusResponse) Descriptor() ([]byte, []int) {
	return file_userProject_proto_rawDescGZIP(), []int{28}
}

func (x *GetUserProjectsByStatusResponse) GetUserProjects() []*UserProject {
	if x != nil {
		return x.UserProjects
	}
	return nil
}

type SetUserProjectArchivedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Archived      bool                   `protobuf:"varint,3,opt,name=archived,proto3" json:"archived,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserProjectArchivedRequest) Reset() {
	*x = SetUserProjectArchivedRequest{}
	mi := &file_userProject_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserProjectArchivedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserProjectArchivedRequest) ProtoMessage() {}

func (x *SetUserProjectArchivedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userProject_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserProjectArchivedRequest.ProtoReflect.Descriptor instead.
func (*SetUserProjectArchivedRequest) Descriptor() ([]byte, []int) {
	return file_userProject_proto_rawDescGZIP(), []int{29}
}

func (x *SetUserProjectArchivedRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *SetUserProjectArchivedRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SetUserProjectArchivedRequest) GetArchived() bool {
	if x != nil {
		return x.Archived
	}
	return false
}

type SetUserProjectArchivedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserProject   *UserProject           `protobuf:"bytes,1,opt,name=user_project,json=userProject,proto3" json:"user_project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserProjectArchivedResponse) Reset() {
	*x = SetUserProjectArchivedResponse{}
	mi := &file_userProject_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserProjectArchivedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserProjectArchivedResponse) ProtoMessage() {}

func (x *SetUserProjectArchivedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userProject_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserProjectArchivedResponse.ProtoReflect.Descriptor instead.
func (*SetUserProjectArchivedResponse) Descriptor() ([]byte, []int) {
	return file_userProject_proto_rawDescGZIP(), []int{30}
}

func (x *SetUserProjectArchivedResponse) GetUserProject() *UserProject {
	if x != nil {
		return x.UserProject
	}
	return nil
}

type SubmitPhaseReviewRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ProjectId string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Email     string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	// Optional: the file the user has open, passed through to the grader as
	// context. Never used to decide anything — purely a hint about where the
	// user is working.
	ActiveFilePath string `protobuf:"bytes,3,opt,name=active_file_path,json=activeFilePath,proto3" json:"active_file_path,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubmitPhaseReviewRequest) Reset() {
	*x = SubmitPhaseReviewRequest{}
	mi := &file_userProject_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitPhaseReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitPhaseReviewRequest) ProtoMessage() {}

func (x *SubmitPhaseReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userProject_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitPhaseReviewRequest.ProtoReflect.Descriptor instead.
func (*SubmitPhaseReviewRequest) Descriptor() ([]byte, []int) {
	return file_userProject_proto_rawDescGZIP(), []int{31}
}

func (x *SubmitPhaseReviewRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *SubmitPhaseReviewRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SubmitPhaseReviewRequest) GetActiveFilePath() string {
	if x != nil {
		return x.ActiveFilePath
	}
	return ""
}

// How one criterion was judged, sent back so the user sees a checklist rather
// than a paragraph. Being told "3 of 5 checks passed, here's which two didn't
// and where" is actionable; a prose verdict is something to argue with.
type CriterionResultProto struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	CriterionId string                 `protobuf:"bytes,1,opt,name=criterion_id,json=criterionId,proto3" json:"criterion_id,omitempty"`
	Text        string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Kind        string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Passed      bool                   `protobuf:"varint,4,opt,name=passed,proto3" json:"passed,omitempty"`
	// Why it failed, or where it was found when it passed.
	Reasoning string `protobuf:"bytes,5,opt,name=reasoning,proto3" json:"reasoning,omitempty"`
	// Populated on a pass — lets the user see what the grader actually looked at,
	// which is also what makes a wrong verdict arguable rather than mysterious.
	EvidencePath  string `protobuf:"bytes,6,opt,name=evidence_path,json=evidencePath,proto3" json:"evidence_path,omitempty"`
	EvidenceLines string `protobuf:"bytes,7,opt,name=evidence_lines,json=evidenceLines,proto3" json:"evidence_lines,omitempty"`
	// Shown only on failure. Names the concept, never the code.
	Hint string `protobuf:"bytes,8,opt,name=hint,proto3" json:"hint,omitempty"`
	// True when grading failed rather than the work — the user should retry, not
	// go looking for a mistake they didn't make.
	Ungraded      bool `protobuf:"varint,9,opt,name=ungraded,proto3" json:"ungraded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CriterionResultProto) Reset() {
	*x = CriterionResultProto{}
	mi := &file_userProject_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CriterionResultProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CriterionResultProto) ProtoMessage() {}

func (x *CriterionResultProto) ProtoReflect() protoreflect.Message {
	mi := &file_userProject_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CriterionResultProto.ProtoReflect.Descriptor instead.
func (*CriterionResultProto) Descriptor() ([]byte, []int) {
	return file_userProject_proto_rawDescGZIP(), []int{32}
}

func (x *CriterionResultProto) GetCriterionId() string {
	if x != nil {
		return x.CriterionId
	}
	return ""
}

func (x *CriterionResultProto) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CriterionResultProto) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *CriterionResultProto) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *CriterionResultProto) GetReasoning() string {
	if x != nil {
		return x.Reasoning
	}
	return ""
}

func (x *CriterionResultProto) GetEvidencePath() string {
	if x != nil {
		return x.EvidencePath
	}
	return ""
}

func (x *CriterionResultProto) GetEvidenceLines() string {
	if x != nil {
		return x.EvidenceLines
	}
	return ""
}

func (x *CriterionResultProto) GetHint() string {
	if x != nil {
		return x.Hint
	}
	return ""
}

func (x *CriterionResultProto) GetUngraded() bool {
	if x != nil {
		return x.Ungraded
	}
	return false
}

type SubmitPhaseReviewResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "met"     — goal judged met; the phase was advanced.
	// "not_met" — goal judged not met; see feedback.
	// "blocked" — never reached the grader: the phase's knowledge checks
	//
	//	aren't all answered correctly yet.
	Verdict string `protobuf:"bytes,1,opt,name=verdict,proto3" json:"verdict,omitempty"`
	// True only when the phase actually advanced. Clients must use this rather
	// than inferring advancement from the feedback text.
	Advanced bool `protobuf:"varint,2,opt,name=advanced,proto3" json:"advanced,omitempty"`
	// The grader's prose explanation, or the reason the submission was blocked.
	Feedback string `protobuf:"bytes,3,opt,name=feedback,proto3" json:"feedback,omitempty"`
	// Authoritative post-review phase number — clients should adopt this rather
	// than incrementing their own local counter.
	CurrentPhase int32 `protobuf:"varint,4,opt,name=current_phase,json=currentPhase,proto3" json:"current_phase,omitempty"`
	// Populated when verdict = "blocked", so the UI can say "3 of 5 correct".
	ChecksTotal   int32 `protobuf:"varint,5,opt,name=checks_total,json=checksTotal,proto3" json:"checks_total,omitempty"`
	ChecksCorrect int32 `protobuf:"varint,6,opt,name=checks_correct,json=checksCorrect,proto3" json:"checks_correct,omitempty"`
	// Per-criterion outcomes, in rubric order. Empty when blocked (nothing was
	// graded) or for phases with no rubric authored.
	Results        []*CriterionResultProto `protobuf:"bytes,7,rep,name=results,proto3" json:"results,omitempty"`
	CriteriaTotal  int32                   `protobuf:"varint,8,opt,name=criteria_total,json=criteriaTotal,proto3" json:"criteria_total,omitempty"`
	CriteriaPassed int32                   `protobuf:"varint,9,opt,name=criteria_passed,json=criteriaPassed,proto3" json:"criteria_passed,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubmitPhaseReviewResponse) Reset() {
	*x = SubmitPhaseReviewResponse{}
	mi := &file_userProject_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitPhaseReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitPhaseReviewResponse) ProtoMessage() {}

func (x *SubmitPhaseReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userProject_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitPhaseReviewResponse.ProtoReflect.Descriptor instead.
func (*SubmitPhaseReviewResponse) Descriptor() ([]byte, []int) {
	return file_userProject_proto_rawDescGZIP(), []int{33}
}

func (x *SubmitPhaseReviewResponse) GetVerdict() string {
	if x != nil {
		return x.Verdict
	}
	return ""
}

func (x *SubmitPhaseReviewResponse) GetAdvanced() bool {
	if x != nil {
		return x.Advanced
	}
	return false
}

func (x *SubmitPhaseReviewResponse) GetFeedback() string {
	if x != nil {
		return x.Feedback
	}
	return ""
}

func (x *SubmitPhaseReviewResponse) GetCurrentPhase() int32 {
	if x != nil {
		return x.CurrentPhase
	}
	return 0
}

func (x *SubmitPhaseReviewResponse) GetChecksTotal() int32 {
	if x != nil {
		return x.ChecksTotal
	}
	return 0
}

func (x *SubmitPhaseReviewResponse) GetChecksCorrect() int32 {
	if x != nil {
		return x.ChecksCorrect
	}
	return 0
}

func (x *SubmitPhaseReviewResponse) GetResults() []*CriterionResultProto {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SubmitPhaseReviewResponse) GetCriteriaTotal() int32 {
	if x != nil {
		return x.CriteriaTotal
	}
	return 0
}

func (x *SubmitPhaseReviewResponse) GetCriteriaPassed() int32 {
	if x != nil {
		return x.CriteriaPassed
	}
	return 0
}

var File_userProject_proto protoreflect.FileDescriptor

const file_userProject_proto_rawDesc = "" +
	"\n" +
	"\x11userProject.proto\x12\vuserProject\"\x91\x01\n" +
	"\x14ShareArtifactRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12!\n" +
	"\fphase_number\x18\x03 \x01(\x05R\vphaseNumber\x12!\n" +
	"\finclude_code\x18\x04 \x01(\bR\vincludeCode\"+\n" +
	"\x15ShareArtifactResponse\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\"A\n" +
	"\x15RevokeArtifactRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\"2\n" +
	"\x16RevokeArtifactResponse\x12\x18\n" +
	"\arevoked\x18\x01 \x01(\bR\arevoked\".\n" +
	"\x16ListMyArtifactsRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"\xed\x01\n" +
	"\x0fMyArtifactProto\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12!\n" +
	"\fproject_name\x18\x03 \x01(\tR\vprojectName\x12!\n" +
	"\fphase_number\x18\x04 \x01(\x05R\vphaseNumber\x12\x1f\n" +
	"\vphase_title\x18\x05 \x01(\tR\n" +
	"phaseTitle\x12!\n" +
	"\finclude_code\x18\x06 \x01(\bR\vincludeCode\x12\x1d\n" +
	"\n" +
	"view_count\x18\a \x01(\x05R\tviewCount\"\x9b\x01\n" +
	"\x13ShareablePhaseProto\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12!\n" +
	"\fproject_name\x18\x02 \x01(\tR\vprojectName\x12!\n" +
	"\fphase_number\x18\x03 \x01(\x05R\vphaseNumber\x12\x1f\n" +
	"\vphase_title\x18\x04 \x01(\tR\n" +
	"phaseTitle\"\xee\x01\n" +
	"\x17ListMyArtifactsResponse\x124\n" +
	"\x06shared\x18\x01 \x03(\v2\x1c.userProject.MyArtifactProtoR\x06shared\x12>\n" +
	"\tshareable\x18\x02 \x03(\v2 .userProject.ShareablePhaseProtoR\tshareable\x12)\n" +
	"\x10profile_unlocked\x18\x03 \x01(\bR\x0fprofileUnlocked\x122\n" +
	"\x15profile_locked_reason\x18\x04 \x01(\tR\x13profileLockedReason\".\n" +
	"\x18GetPublicArtifactRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\"\x8a\x01\n" +
	"\x14PublicCriterionProto\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12#\n" +
	"\revidence_path\x18\x03 \x01(\tR\fevidencePath\x12%\n" +
	"\x0eevidence_lines\x18\x04 \x01(\tR\revidenceLines\"?\n" +
	"\x0fPublicFileProto\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\xc7\x03\n" +
	"\x19GetPublicArtifactResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x18\n" +
	"\arevoked\x18\x02 \x01(\bR\arevoked\x12\x1f\n" +
	"\vauthor_name\x18\x03 \x01(\tR\n" +
	"authorName\x12!\n" +
	"\fproject_name\x18\x04 \x01(\tR\vprojectName\x12!\n" +
	"\fphase_number\x18\x05 \x01(\x05R\vphaseNumber\x12\x1f\n" +
	"\vphase_title\x18\x06 \x01(\tR\n" +
	"phaseTitle\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12=\n" +
	"\bcriteria\x18\b \x03(\v2!.userProject.PublicCriterionProtoR\bcriteria\x121\n" +
	"\x14explanation_question\x18\t \x01(\tR\x13explanationQuestion\x12-\n" +
	"\x12explanation_answer\x18\n" +
	" \x01(\tR\x11explanationAnswer\x122\n" +
	"\x05files\x18\v \x03(\v2\x1c.userProject.PublicFileProtoR\x05files\"(\n" +
	"\x10GetGrowthRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"e\n" +
	"\x13EraRequirementProto\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x10\n" +
	"\x03met\x18\x02 \x01(\bR\x03met\x12\x12\n" +
	"\x04have\x18\x03 \x01(\x05R\x04have\x12\x12\n" +
	"\x04need\x18\x04 \x01(\x05R\x04need\"|\n" +
	"\x15UnexplainedPhaseProto\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12!\n" +
	"\fproject_name\x18\x02 \x01(\tR\vprojectName\x12!\n" +
	"\fphase_number\x18\x03 \x01(\x05R\vphaseNumber\"\xa2\x03\n" +
	"\x11GetGrowthResponse\x12\x14\n" +
	"\x05build\x18\x01 \x01(\x05R\x05build\x12\x1e\n" +
	"\n" +
	"understand\x18\x02 \x01(\x05R\n" +
	"understand\x12\x18\n" +
	"\aexplore\x18\x03 \x01(\x05R\aexplore\x12\x12\n" +
	"\x04show\x18\x04 \x01(\x05R\x04show\x12\x19\n" +
	"\bera_name\x18\x05 \x01(\tR\aeraName\x12\x1b\n" +
	"\tera_blurb\x18\x06 \x01(\tR\beraBlurb\x12\x1b\n" +
	"\tera_index\x18\a \x01(\x05R\beraIndex\x12\"\n" +
	"\rnext_era_name\x18\b \x01(\tR\vnextEraName\x12M\n" +
	"\x11next_requirements\x18\t \x03(\v2 .userProject.EraRequirementProtoR\x10nextRequirements\x12\x1b\n" +
	"\tfog_count\x18\n" +
	" \x01(\x05R\bfogCount\x12D\n" +
	"\vunexplained\x18\v \x03(\v2\".userProject.UnexplainedPhaseProtoR\vunexplained\"p\n" +
	"\x16StartCheckpointRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12!\n" +
	"\fphase_number\x18\x03 \x01(\x05R\vphaseNumber\"Z\n" +
	"\x17StartCheckpointResponse\x12#\n" +
	"\rcheckpoint_id\x18\x01 \x01(\tR\fcheckpointId\x12\x1a\n" +
	"\bquestion\x18\x02 \x01(\tR\bquestion\"l\n" +
	"\x17SubmitCheckpointRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12#\n" +
	"\rcheckpoint_id\x18\x02 \x01(\tR\fcheckpointId\x12\x16\n" +
	"\x06answer\x18\x03 \x01(\tR\x06answer\"y\n" +
	"\x18SubmitCheckpointResponse\x12\x16\n" +
	"\x06passed\x18\x01 \x01(\bR\x06passed\x12\x1a\n" +
	"\bfeedback\x18\x02 \x01(\tR\bfeedback\x12)\n" +
	"\x10missing_concepts\x18\x03 \x03(\tR\x0fmissingConcepts\"\x8c\x01\n" +
	"\x18CreateUserProjectRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12#\n" +
	"\rcurrent_phase\x18\x04 \x01(\x05R\fcurrentPhase\"5\n" +
	"\x19CreateUserProjectResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\":\n" +
	"\x19GetUserProjectByIdRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"Y\n" +
	"\x1aGetUserProjectByIdResponse\x12;\n" +
	"\fuser_project\x18\x01 \x01(\v2\x18.userProject.UserProjectR\vuserProject\"1\n" +
	"\x19GetAllUserProjectsRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"[\n" +
	"\x1aGetAllUserProjectsResponse\x12=\n" +
	"\ruser_projects\x18\x01 \x03(\v2\x18.userProject.UserProjectR\fuserProjects\"\x9b\x01\n" +
	"\vUserProject\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12#\n" +
	"\rcurrent_phase\x18\x04 \x01(\x05R\fcurrentPhase\x12\x1a\n" +
	"\barchived\x18\x05 \x01(\bR\barchived\"N\n" +
	"\x1eGetUserProjectsByStatusRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"`\n" +
	"\x1fGetUserProjectsByStatusResponse\x12=\n" +
	"\ruser_projects\x18\x01 \x03(\v2\x18.userProject.UserProjectR\fuserProjects\"p\n" +
	"\x1dSetUserProjectArchivedRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\barchived\x18\x03 \x01(\bR\barchived\"]\n" +
	"\x1eSetUserProjectArchivedResponse\x12;\n" +
	"\fuser_project\x18\x01 \x01(\v2\x18.userProject.UserProjectR\vuserProject\"y\n" +
	"\x18SubmitPhaseReviewRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12(\n" +
	"\x10active_file_path\x18\x03 \x01(\tR\x0eactiveFilePath\"\x93\x02\n" +
	"\x14CriterionResultProto\x12!\n" +
	"\fcriterion_id\x18\x01 \x01(\tR\vcriterionId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x16\n" +
	"\x06passed\x18\x04 \x01(\bR\x06passed\x12\x1c\n" +
	"\treasoning\x18\x05 \x01(\tR\treasoning\x12#\n" +
	"\revidence_path\x18\x06 \x01(\tR\fevidencePath\x12%\n" +
	"\x0eevidence_lines\x18\a \x01(\tR\revidenceLines\x12\x12\n" +
	"\x04hint\x18\b \x01(\tR\x04hint\x12\x1a\n" +
	"\bungraded\x18\t \x01(\bR\bungraded\"\xe9\x02\n" +
	"\x19SubmitPhaseReviewResponse\x12\x18\n" +
	"\averdict\x18\x01 \x01(\tR\averdict\x12\x1a\n" +
	"\badvanced\x18\x02 \x01(\bR\badvanced\x12\x1a\n" +
	"\bfeedback\x18\x03 \x01(\tR\bfeedback\x12#\n" +
	"\rcurrent_phase\x18\x04 \x01(\x05R\fcurrentPhase\x12!\n" +
	"\fchecks_total\x18\x05 \x01(\x05R\vchecksTotal\x12%\n" +
	"\x0echecks_correct\x18\x06 \x01(\x05R\rchecksCorrect\x12;\n" +
	"\aresults\x18\a \x03(\v2!.userProject.CriterionResultProtoR\aresults\x12%\n" +
	"\x0ecriteria_total\x18\b \x01(\x05R\rcriteriaTotal\x12'\n" +
	"\x0fcriteria_passed\x18\t \x01(\x05R\x0ecriteriaPassed2\x8f\n" +
	"\n" +
	"\x12UserProjectService\x12^\n" +
	"\rCreateProject\x12%.userProject.CreateUserProjectRequest\x1a&.userProject.CreateUserProjectResponse\x12e\n" +
	"\x12GetUserProjectById\x12&.userProject.GetUserProjectByIdRequest\x1a'.userProject.GetUserProjectByIdResponse\x12e\n" +
	"\x12GetAllUserProjects\x12&.userProject.GetAllUserProjectsRequest\x1a'.userProject.GetAllUserProjectsResponse\x12t\n" +
	"\x17GetUserProjectsByStatus\x12+.userProject.GetUserProjectsByStatusRequest\x1a,.userProject.GetUserProjectsByStatusResponse\x12q\n" +
	"\x16SetUserProjectArchived\x12*.userProject.SetUserProjectArchivedRequest\x1a+.userProject.SetUserProjectArchivedResponse\x12b\n" +
	"\x11SubmitPhaseReview\x12%.userProject.SubmitPhaseReviewRequest\x1a&.userProject.SubmitPhaseReviewResponse\x12J\n" +
	"\tGetGrowth\x12\x1d.userProject.GetGrowthRequest\x1a\x1e.userProject.GetGrowthResponse\x12\\\n" +
	"\x0fStartCheckpoint\x12#.userProject.StartCheckpointRequest\x1a$.userProject.StartCheckpointResponse\x12_\n" +
	"\x10SubmitCheckpoint\x12$.userProject.SubmitCheckpointRequest\x1a%.userProject.SubmitCheckpointResponse\x12V\n" +
	"\rShareArtifact\x12!.userProject.ShareArtifactRequest\x1a\".userProject.ShareArtifactResponse\x12Y\n" +
	"\x0eRevokeArtifact\x12\".userProject.RevokeArtifactRequest\x1a#.userProject.RevokeArtifactResponse\x12\\\n" +
	"\x0fListMyArtifacts\x12#.userProject.ListMyArtifactsRequest\x1a$.userProject.ListMyArtifactsResponse\x12b\n" +
	"\x11GetPublicArtifact\x12%.userProject.GetPublicArtifactRequest\x1a&.userProject.GetPublicArtifactResponseB\x10Z\x0egateway/pkg/pbb\x06proto3"

var (
	file_userProject_proto_rawDescOnce sync.Once
	file_userProject_proto_rawDescData []byte
)

func file_userProject_proto_rawDescGZIP() []byte {
	file_userProject_proto_rawDescOnce.Do(func() {
		file_userProject_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_userProject_proto_rawDesc), len(file_userProject_proto_rawDesc)))
	})
	return file_userProject_proto_rawDescData
}

var file_userProject_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_userProject_proto_goTypes = []any{
	(*ShareArtifactRequest)(nil),            // 0: userProject.ShareArtifactRequest
	(*ShareArtifactResponse)(nil),           // 1: userProject.ShareArtifactResponse
	(*RevokeArtifactRequest)(nil),           // 2: userProject.RevokeArtifactRequest
	(*RevokeArtifactResponse)(nil),          // 3: userProject.RevokeArtifactResponse
	(*ListMyArtifactsRequest)(nil),          // 4: userProject.ListMyArtifactsRequest
	(*MyArtifactProto)(nil),                 // 5: userProject.MyArtifactProto
	(*ShareablePhaseProto)(nil),             // 6: userProject.ShareablePhaseProto
	(*ListMyArtifactsResponse)(nil),         // 7: userProject.ListMyArtifactsResponse
	(*GetPublicArtifactRequest)(nil),        // 8: userProject.GetPublicArtifactRequest
	(*PublicCriterionProto)(nil),            // 9: userProject.PublicCriterionProto
	(*PublicFileProto)(nil),                 // 10: userProject.PublicFileProto
	(*GetPublicArtifactResponse)(nil),       // 11: userProject.GetPublicArtifactResponse
	(*GetGrowthRequest)(nil),                // 12: userProject.GetGrowthRequest
	(*EraRequirementProto)(nil),             // 13: userProject.EraRequirementProto
	(*UnexplainedPhaseProto)(nil),           // 14: userProject.UnexplainedPhaseProto
	(*GetGrowthResponse)(nil),               // 15: userProject.GetGrowthResponse
	(*StartCheckpointRequest)(nil),          // 16: userProject.StartCheckpointRequest
	(*StartCheckpointResponse)(nil),         // 17: userProject.StartCheckpointResponse
	(*SubmitCheckpointRequest)(nil),         // 18: userProject.SubmitCheckpointRequest
	(*SubmitCheckpointResponse)(nil),        // 19: userProject.SubmitCheckpointResponse
	(*CreateUserProjectRequest)(nil),        // 20: userProject.CreateUserProjectRequest
	(*CreateUserProjectResponse)(nil),       // 21: userProject.CreateUserProjectResponse
	(*GetUserProjectByIdRequest)(nil),       // 22: userProject.GetUserProjectByIdRequest
	(*GetUserProjectByIdResponse)(nil),      // 23: userProject.GetUserProjectByIdResponse
	(*GetAllUserProjectsRequest)(nil),       // 24: userProject.GetAllUserProjectsRequest
	(*GetAllUserProjectsResponse)(nil),      // 25: userProject.GetAllUserProjectsResponse
	(*UserProject)(nil),                     // 26: userProject.UserProject
	(*GetUserProjectsByStatusRequest)(nil),  // 27: userProject.GetUserProjectsByStatusRequest
	(*GetUserProjectsByStatusResponse)(nil), // 28: userProject.GetUserProjectsByStatusResponse
	(*SetUserProjectArchivedRequest)(nil),   // 29: userProject.SetUserProjectArchivedRequest
	(*SetUserProjectArchivedResponse)(nil),  // 30: userProject.SetUserProjectArchivedResponse
	(*SubmitPhaseReviewRequest)(nil),        // 31: userProject.SubmitPhaseReviewRequest
	(*CriterionResultProto)(nil),            // 32: userProject.CriterionResultProto
	(*SubmitPhaseReviewResponse)(nil),       // 33: userProject.SubmitPhaseReviewResponse
}
var file_userProject_proto_depIdxs = []int32{
	5,  // 0: userProject.ListMyArtifactsResponse.shared:type_name -> userProject.MyArtifactProto
	6,  // 1: userProject.ListMyArtifactsResponse.shareable:type_name -> userProject.ShareablePhaseProto
	9,  // 2: userProject.GetPublicArtifactResponse.criteria:type_name -> userProject.PublicCriterionProto
	10, // 3: userProject.GetPublicArtifactResponse.files:type_name -> userProject.PublicFileProto
	13, // 4: userProject.GetGrowthResponse.next_requirements:type_name -> userProject.EraRequirementProto
	14, // 5: userProject.GetGrowthResponse.unexplained:type_name -> userProject.UnexplainedPhaseProto
	26, // 6: userProject.GetUserProjectByIdResponse.user_project:type_name -> userProject.UserProject
	26, // 7: userProject.GetAllUserProjectsResponse.user_projects:type_name -> userProject.UserProject
	26, // 8: userProject.GetUserProjectsByStatusResponse.user_projects:type_name -> userProject.UserProject
	26, // 9: userProject.SetUserProjectArchivedResponse.user_project:type_name -> userProject.UserProject
	32, // 10: userProject.SubmitPhaseReviewResponse.results:type_name -> userProject.CriterionResultProto
	20, // 11: userProject.UserProjectService.CreateProject:input_type -> userProject.CreateUserProjectRequest
	22, // 12: userProject.UserProjectService.GetUserProjectById:input_type -> userProject.GetUserProjectByIdRequest
	24, // 13: userProject.UserProjectService.GetAllUserProjects:input_type -> userProject.GetAllUserProjectsRequest
	27, // 14: userProject.UserProjectService.GetUserProjectsByStatus:input_type -> userProject.GetUserProjectsByStatusRequest
	29, // 15: userProject.UserProjectService.SetUserProjectArchived:input_type -> userProject.SetUserProjectArchivedRequest
	31, // 16: userProject.UserProjectService.SubmitPhaseReview:input_type -> userProject.SubmitPhaseReviewRequest
	12, // 17: userProject.UserProjectService.GetGrowth:input_type -> userProject.GetGrowthRequest
	16, // 18: userProject.UserProjectService.StartCheckpoint:input_type -> userProject.StartCheckpointRequest
	18, // 19: userProject.UserProjectService.SubmitCheckpoint:input_type -> userProject.SubmitCheckpointRequest
	0,  // 20: userProject.UserProjectService.ShareArtifact:input_type -> userProject.ShareArtifactRequest
	2,  // 21: userProject.UserProjectService.RevokeArtifact:input_type -> userProject.RevokeArtifactRequest
	4,  // 22: userProject.UserProjectService.ListMyArtifacts:input_type -> userProject.ListMyArtifactsRequest
	8,  // 23: userProject.UserProjectService.GetPublicArtifact:input_type -> userProject.GetPublicArtifactRequest
	21, // 24: userProject.UserProjectService.CreateProject:output_type -> userProject.CreateUserProjectResponse
	23, // 25: userProject.UserProjectService.GetUserProjectById:output_type -> userProject.GetUserProjectByIdResponse
	25, // 26: userProject.UserProjectService.GetAllUserProjects:output_type -> userProject.GetAllUserProjectsResponse
	28, // 27: userProject.UserProjectService.GetUserProjectsByStatus:output_type -> userProject.GetUserProjectsByStatusResponse
	30, // 28: userProject.UserProjectService.SetUserProjectArchived:output_type -> userProject.SetUserProjectArchivedResponse
	33, // 29: userProject.UserProjectService.SubmitPhaseReview:output_type -> userProject.SubmitPhaseReviewResponse
	15, // 30: userProject.UserProjectService.GetGrowth:output_type -> userProject.GetGrowthResponse
	17, // 31: userProject.UserProjectService.StartCheckpoint:output_type -> userProject.StartCheckpointResponse
	19, // 32: userProject.UserProjectService.SubmitCheckpoint:output_type -> userProject.SubmitCheckpointResponse
	1,  // 33: userProject.UserProjectService.ShareArtifact:output_type -> userProject.ShareArtifactResponse
	3,  // 34: userProject.UserProjectService.RevokeArtifact:output_type -> userProject.RevokeArtifactResponse
	7,  // 35: userProject.UserProjectService.ListMyArtifacts:output_type -> userProject.ListMyArtifactsResponse
	11, // 36: userProject.UserProjectService.GetPublicArtifact:output_type -> userProject.GetPublicArtifactResponse
	24, // [24:37] is the sub-list for method output_type
	11, // [11:24] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_userProject_proto_init() }
func file_userProject_proto_init() {
	if File_userProject_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_userProject_proto_rawDesc), len(file_userProject_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_userProject_proto_goTypes,
		DependencyIndexes: file_userProject_proto_depIdxs,
		MessageInfos:      file_userProject_proto_msgTypes,
	}.Build()
	File_userProject_proto = out.File
	file_userProject_proto_goTypes = nil
	file_userProject_proto_depIdxs = nil
}
